### ISSUE TITLE
Windows 10 security policy blocks Evolve CLI

### ISSUE THREAD

**Issue by tswiatowiec** [lecaillon/Evolve#103]
Hello.
My windows blocks evolve CLI  from running. It’s probably because no info about the assembly is filled (publisher, etc).
I cannot change Windows Defender settings, it’s a corporate computer.
Any ideas ?
![4](https://user-images.githubusercontent.com/47893439/53248495-28ebca80-36b6-11e9-98d2-9ae9e6075673.png)

**Comment by lecaillon** [comment]
@tswiatowiec  Thanks for your feedback. I don't know what are the policy about running exe in Windows 10. You can tell to your boss I think it's a bit awkward that a dev is not local admin of its computer ;)

Anyway I'm going to search a solution. If you have any idea, be my guest

**Comment by tswiatowiec** [comment]
Ok, I fixed it :)
Right click on exe -> properties. There's a note saying "this file might be blocked..." and Unlock checkbox.
It worked. Thanks :)

**Comment by lecaillon** [comment]
Anyway I think if I published the CLI with a valid certificate you wouldn't have to do this. I'll think about it.
