### ISSUE TITLE
Use configuration file for the Evolve command line utility

### ISSUE THREAD

**Issue by kippm** [lecaillon/Evolve#104]
Hi,

is it possible to use a configuration file when using the Evolve command line utility instead of the command line options?

For the different environments I want to deploy to, I think it is cleaner to have different configuration files, than, for example, to generate different batch files with this different command line options for the different environments.

**Comment by lecaillon** [comment]
Hi, 

Thanks for your feedback. 
Currently it is not possible to use a config file with the CLI.

Anyway, could you be more specific about your use case and the feature you would have wanted:
- how the CLI will know what config file to take ?
- is it always a file called `evolve.json` or a parameter in the commanline option, say `--config-file`
- in case there is some duplicate parameters defined by the user, between the commandline args CLI and the config file which has the priority ?
etc etc :)

**Comment by kippm** [comment]
When we build our applications we normally have config files for the different environments. In this case something like evolve.dev.json, evolve.tst.json and evolve.prod.json. During the release, the environment that is chosen will decide which file to copy as the main one, e.g. copied to evolve.json. This is the file that will be used by the application. This way the deploy command is always the same.

- use a --config-file to specify the file name. In the case above it would be --confi-file evolve.json
- I think that the best is that you either specify a --config-file or use the other arguments. 
- In case a mix will be allowed of the --config-file and other arguments, then the arguments should override the config file.

**Comment by GeirGrusom** [comment]
Couldn't you just pipe a text file into the CLI?

**Comment by lecaillon** [comment]
@GeirGrusom Evolve currently uses this package to handle command line stuff: `McMaster.Extensions.CommandLineUtils`

This package exposes that feature to "import" args into the CLI: https://natemcmaster.github.io/CommandLineUtils/docs/response-file-parsing.html?tabs=using-attributes

Was that what you were talking about ?

**Comment by GeirGrusom** [comment]
No. I haven't use the CLI before, but I assume that you can control pretty much everything from there. Instead of a configuration file you could write a script that performs commands, and if the CLI expects user input you can simply pipe that into the process.

It's kind of a big reason why CLI's are useful. Even the most interactive CLI tools can be automated without any support for it in the CLI itself.

If for example you have a CLI tool that asks the user for a name two write "Hello , {name}!" You can just pipe the name into it like this:

```echo World | greeting.exe```

If the CLI takes arguments for all of this it's also trivial to automate that. No reason, I think, for a configuration file for CLI tools (for the most part) because it can probably already be automated by a script. To me it seems like wasted time that would be better put in more productive areas.

**Comment by lecaillon** [comment]
thanks @GeirGrusom 
I'm not very familiar with CLI in general. Your point is clear and it is the default behavior I've seen searching for examples.
I will keep that in mind when I'll implement that feature

thanks again

**Comment by kippm** [comment]
@GeirGrusom I've tried to run evolve.exe @args.txt but it didn't seem to pick up the arguments in the file.
I was using the Windows exe btw.
Anyway, I think it is cleaner to work with a real configuration file. But that is just my preference.

**Comment by lecaillon** [comment]
@kippm I noticed the option is not activated in Evolve 2.2
I've just tested successfully in my current branch the command:
```
evolve.exe @args.txt
```
Too bad... It will be availlable in Evolve 2.3

By the way, 2 options are available to treat arguments in the response file:
- `ParseArgsAsSpaceSeparated`: Multiple arguments may appear on one line. Arguments are separate by spaces.
- `ParseArgsAsLineSeparated`: Each line in the file is treated as an argument, regardless of whitespace on the line.

Which one do you prefer ?

**Comment by lecaillon** [comment]
It is worth noted that if a parameter is declared both in the command line arg and the response file an error is thrown. @kippm

**Comment by kippm** [comment]
> @kippm I noticed the option is not activated in Evolve 2.2
> I've just tested successfully in my current branch the command:
> 
> ```
> evolve.exe @args.txt
> ```
> Too bad... It will be availlable in **Evolve 2.3**
> 
> By the way, 2 options are available to treat arguments in the response file:
> 
> * `ParseArgsAsSpaceSeparated`: Multiple arguments may appear on one line. Arguments are separate by spaces.
> * `ParseArgsAsLineSeparated`: Each line in the file is treated as an argument, regardless of whitespace on the line.
> 
> Which one do you prefer ?
> 
> Examples can be found here: https://natemcmaster.github.io/CommandLineUtils/docs/response-file-parsing.html?tabs=using-attributes

I looked at the examples and didn't like the way the Line separated look, because of the fact that the argument and value are not on the same line. So that would leave the space separated option. However, if there are many arguments, this will become unreadable.

**Comment by lecaillon** [comment]
You can find an alpha version of Evolve 2.3 CLI there:
- [Windows](https://ci.appveyor.com/api/buildjobs/m54cxdt1kkfvqnwa/artifacts/dist%2Fevolve.exe)
- [Linux](https://lecaillon.visualstudio.com/8e869842-250f-4687-b649-e8429bf233e8/_apis/build/builds/236/artifacts?artifactName=dist&fileId=14D7CF3FD0BB29886274D2B85E82F32087F63ECEBD94094AD8A88797BD10C8A602&fileName=evolve&api-version=5.0-preview.3)

This version enables file argument parsing (with option `ParseArgsAsSpaceSeparated`).
*After testing it, I feel it very convienent not to have to pass all the parameters in the command line. You can now easily just change the Evolve Command*:
```
evolve info @args.txt
```
```
evolve migrate @args.txt
```

And the new command `info` that displays all applied migrations for a given database.

@kippm  Don't hesitate to give me your feedback about it.

**Comment by kippm** [comment]
Works as expected. Definitely an improvement over specifying command line arguments.
However, my preference would still go to a line based config file, where the key and value are on one line.
For example
connection-string=Server=.;Database=Test;
location=D:\sql_scripts
...
...

This would definitely improve readability, in case your will be using more configuration settings.

**Comment by lecaillon** [comment]
Great. This feature will be officially available in the next release as it improves the CLI and at the same time allows Evolve to continue to use the CLI args attribute validation, ordering and parsing capabilities of the `CommandLineUtils` package it lays on.

Thanks again for the feedback!
