### ISSUE TITLE
Why there is a dependency upon .net 3.5 ?

### ISSUE THREAD

**Issue by oooolivierrrr** [lecaillon/Evolve#105]
I fail to see why we need the 3.5 framework. I'd like to remove it.

**Comment by lecaillon** [comment]
Evolve NuGet package comes with 3 versions of Evolve for 3 differents needs.

Supported "Frameworks"
    .NET 3.5+
    .NET 4.6.1+
    .NET Standard 2.0

If your application uses .NET Core, NuGet will automatically take the Evolve .NET Standard version for example.
So Evolve is not tied to .NET 3.5, but Evolve targets 3 differents framework. And one of these, is .NET 3.5 for people who can not migrate to the latest versions of .NET.

**Comment by oooolivierrrr** [comment]
oui mais pour ceux qui veulent contribuer c’est un peu chiant.

for those who w nuts to contribute, it’s an hurdle


________________________________

**Comment by lecaillon** [comment]
duly noted :)

ps: you could just remove this target version of the framework, the time of your dev.
