### ISSUE TITLE
CLI Blocking on first build with evolve

### ISSUE THREAD

**Issue by jouana** [lecaillon/Evolve#110]
Hi,

We use Evolve with SQLite and when we make a first build Evolve create the database file and did his migration well, but don't leave his task.

 We must kill Evolve process to end up our first build, this make some issue with Jenkins and block our builds.

I will try to find some time to investigate this issue.

Btw thanks for the job done.

Regards,
Antoine

**Comment by lecaillon** [comment]
Ok that is strange

**Comment by jouana** [comment]
Hi, sorry for my late.

It's on Windows with EvolveTask in csproj.
When the db file doesn't exist for SQLite then Evolve create it and apply migrate but it doesn't display log and waiting for something.

I have sometime today, I'll try to fix it en push a PR

Regards

**Comment by jouana** [comment]
Hi,

It take some time because it's hard to debug.
So in EvolveBoot (Task) a fork (Process) is done to execute Evolve cli, when no db file exist and SQlite create it then the executable freeze.

When we execute the cli or lib directly all done well

I think it's a problem form Process and output management or an issue with SQlite and managed resource.

I'll try to make some refactoring to use directly the library rather than cli.

(sry my english is aproximate)

Regards

**Comment by lecaillon** [comment]
Thank you for the time you spend on this issue. I will try to take some time on this too and give you some feedback if there is any news.

**Comment by lecaillon** [comment]
I don't reproduce the issue. I used this [sample](https://github.com/lecaillon/Evolve/tree/master/samples/AspNetCoreSample_MSBuild) which is closed to what you describe.
