### ISSUE TITLE
Expose DatabaseHelperFactory as an extensible interface

### ISSUE THREAD

**Issue by jinhong-** [lecaillon/Evolve#111]
Any plans to make it possible for third parties to add their own custom Database migration implementations? At the moment it is impossible to extend because DatabaseHelperFactory is a static class. If it is converted to an interface, this could be easily extended by third parties to add or customize their own Database migrations

**Comment by jinhong-** [comment]
Check out PR #112

**Comment by jinhong-** [comment]
Build failed because tests were not fixed. Let me know if this idea is okay with you. I will fix the tests as soon as i get my hands on a windows computer :)

**Comment by lecaillon** [comment]
Hi @jinhong- 
Before we talk technically, can you give me an example of what you try to achieve by that please ?
Which use cases do we address here ?

**Comment by jinhong-** [comment]
There are 2 use cases
1. I was thinking of adding a new provider for another database. For eg, ArangoDB. 
2. Also when attempting to use the migrations with CockroachDB, i encountered some errors which required me to modify/extend the PostgreSQL providers. At the moment there is no way to modify it without changing the source codes and then recompiling it

**Comment by lecaillon** [comment]
Ok I understand. And indeed you cannot extend it that way, and it is because it is not meant for it.
However, I will be pleased to work with you on the support of ArangoDB and CockroachDB.
Would not it be better to add those databases and share it with the community, rather than develop a "personal" extension ? 
I already go through this process for Cassandra. And it is now fully supported by Evolve.

I must add that I don't know those 2 databases (only by name), so I cannot assure you they are fully compatible with all Evolve ecosystem but at least give it a try !

What do you think @jinhong- ?

**Comment by lecaillon** [comment]
@jinhong- If it wasn't clear enough, give it a try **together** if you want :)

**Comment by jinhong-** [comment]
@lecaillon  It's quite clear to me. We could definitely work on this together and i am all for sharing these new database implementations.
There still remains the issue of speed of development/release. For eg, I need to develop this by the end of next week. To develop it within the same repository, it would have to adhere to the same release cycle as this repository. As an extension it could move under a different release cycle.
It would be great if this project can follow similar models to such that of Microsoft.Extensions.Configuration, where it provides an extensibility interface to allow people to build and develop their own configuration providers. If you go into NuGet and browse, you will see that people have created tons of customized providers: k8s configmap, secrets, hocon, spring config server, etc which extends from the base set of Configuration APIs.
Ultimately people are still contributed back to making the project better, and they could release at their own pace

**Comment by jinhong-** [comment]
On the note of CockroachDB, so far i managed to get it to work by using PostgreSQL provider since it is compatible on the protocol layer. There was one issue with the Metadata table with the id column being set to serial, since in postgres serial represents a 32bit number but in cockroach it represents a 64bit number. So far i managed to get away by setting a session variable before migration by calling
```SET experimental_serial_normalization = sql_sequence;```
Which will force the current session to generate ids using the same format as postgres. However this is not recommended as this will make every single table accessed and created in that session to have the same effect. There are 2 possible ways to properly fix this:
1. Change library's datatype to support int64
2. Create a sequence in cockroachdb and use that to generate the increment

**Comment by lecaillon** [comment]
I've created a new issue for CockroachDB: [114](https://github.com/lecaillon/Evolve/issues/114)
Let this issue only be about Evolve extensibility, shall we ?

**Comment by jinhong-** [comment]
Okay!

**Comment by lecaillon** [comment]
I don't think Evolve should be extensible. It is composed of 3 parts (Evolve, MSBuild, and the CLI) that should change at the same time. More over The fact that is has one repository allow all databases to get new features at the same time. And extensions cannot guarantee any of it.
