### ISSUE TITLE
Add CockroachDB support

### ISSUE THREAD

**Issue by lecaillon** [lecaillon/Evolve#115]
On the note of CockroachDB, so far i managed to get it to work by using PostgreSQL provider since it is compatible on the protocol layer. There was one issue with the Metadata table with the id column being set to serial, since in postgres serial represents a 32bit number but in cockroach it represents a 64bit number. So far i managed to get away by setting a session variable before migration by calling
```SET experimental_serial_normalization = sql_sequence;```
Which will force the current session to generate ids using the same format as postgres. However this is not recommended as this will make every single table accessed and created in that session to have the same effect. There are 2 possible ways to properly fix this:
1. Change library's datatype to support int64
2. Create a sequence in cockroachdb and use that to generate the increment

_Originally posted by @jinhong- in https://github.com/lecaillon/Evolve/issues/111#issuecomment-480667671_

**Comment by lecaillon** [comment]
@jinhong- It is a good news that CockroachDB is designed to be compatible with PostgreSQL. It will be less work on our side. But I think we have to create an independent Evolve driver, a new `CockroachDBDatabase`. It will be easier to implement its specificities.
I can quickly build a branch and share it with you. What do you think ?

Concerning the `id` column of the Metadata table, the [CockroachDB documentation](https://www.cockroachlabs.com/docs/stable/serial.html) explains that the multiple translation modes for `SERIAL` may be removed in subsequent releases.  Try not use it then. 

So a third solution would be to use the same implementation than in the [Evolve Cassandra provider](https://github.com/lecaillon/Evolve/blob/329ee3df6fc9b3046c9c2f0a604196f585622262/src/Evolve/Dialect/Cassandra/CassandraMetadataTable.cs#L57). The only inconvenient is obviously the generated ids are random. Because, who cares really ?

**Comment by jinhong-** [comment]
Look at #116

**Comment by jinhong-** [comment]
Works alright as far as i tested it. I made use of the sequence feature to generate the id instead. This allowed me to specify the datatype as well as the limiting the running number to Int32.Max. The drawback is the insertion performance with relation to CockroachDb but this isn't a problem considering we won't be doing anything more than a couple of inserts every now and then

**Comment by lecaillon** [comment]
> Let me know what else i can do to get this in quickly as i really need this for my current project

@jinhong- What about tests ?

Evolve use Docker (how original) to create a new database that it can use to run its integration tests. So you have to add a new dedicated `CockroachDBContainer` and `CockroachDBFixture` in the Evolve.Tests/Infrastructure folder. Don't forget to add a new Xunit `CollectionDefinition` at the end of the `TestContext` class and later define constants for your CockroachDB scripts.

Then you can create a new Integration/CockroachDB folder and add your tests. Integration tests are all made in the same spirit between databases. So don't hesitate to look at what it is made in Integration/PostgreSQL for example. You can probably re-use most of the migration scripts of the PostgreSQL/Resources folder.

Integration tests are grouped into 2 classes. Start with `DialectTest` because it does not need any scripts to run.

And feel free to ask me questions if you need

**Comment by jinhong-** [comment]
Will do. I don't always have access to a windows machine so doing that might be challenging. I will add those once i am able to

**Comment by lecaillon** [comment]
If it is because the .NET target frameworks of the Evolve project. Remove them temporarily.
```
<TargetFrameworks>net35;net461;netstandard2.0</TargetFrameworks>
```

Otherwise I don't see what can prevent you to run those tests. FYI the Azure Pipelines build runs on a Linux VM.

**Comment by lecaillon** [comment]
A tricky part of a new Evolve database provider is the `DatabaseHelper.TryAcquireApplicationLock` method implementation. 
Evolve uses a session level lock to coordinate the migrations on multiple nodes. This prevents two distinct Evolve executions from executing a migration on the same database at the same time.

You should ensure this part is compatible with PostgreSQL.

**Comment by lecaillon** [comment]
Finally you can update the Evolve.Cli project according to this new database support. It shouldn't be too much work. In my mind just add a new database option in the list.

**Comment by jinhong-** [comment]
While running the tests, i was blocked by a couple of issues:
1. ```DatabaseHelper.TryAcquireApplicationLock``` indeed does not work since cockroachdb does not really honor the functions even though it did not throw back any errors
2. Looks like the system revolves around the ability to create and delete schemas. Cockroachdb however do not actually support the concepts of creating or deleting schemas. Is there any way to not use schemas in evolve or alternatively, could i model database as schemas instead? Do you see any issues with that approach?

**Comment by lecaillon** [comment]
1. Like I said the idea of that function is to prevent execution of multiple migration at the same time. I found this [link](https://forum.cockroachlabs.com/t/alternatives-to-pg-advisory-locks/742) that could be inspiring for us.

2. I don't know Cockroach enought but if the schema concept does not exists, that's fine. We can implement an alternative. You should read the Evolve Cassandra code, because it is the only example in Evolve of a "non relationnal" database, with its own concepts. It could give you ideas for Cockroach

**Comment by lecaillon** [comment]
> Looks like the system revolves around the ability to create and delete schemas. Cockroachdb however do not actually support the concepts of creating or deleting schemas. Is there any way to not use schemas in evolve or alternatively, could i model database as schemas instead? Do you see any issues with that approach?

Good idea ! I'm working on it

**Comment by lecaillon** [comment]
@jinhong- I think I can have a version of Evolve that supports CockroachDB by the end of the week. It only still lacks of tests currently to be "releasable". But it's in good way.
There's only one issue left: how can we assure that one cannot run multiple Evolve migration at the same time. (For example as many times as you have application container, when you use Evolve in the startup of your app). I imagine a lock that only the first Evolve instance can take could do the trick (cf: pg_try_advisory_lock for the PostgreSQL version), but how "implement" that in CockroachDB ? Can you work on it ?

**Comment by jinhong-** [comment]
Hi @lecaillon, been a busy few weeks for me.. In terms of locking, i think the way forward is to manually do locks.. The logic would work something like this:
1. Have a table containing locks, with a lock id, lock holder id and lock expiry
2. When `DatabaseHelper.TryAcquireApplicationLock` is called, lookup unique lockid and ensure lock is not held based on criteria that lock holder is empty or lock has expired
3. Then, create or update lock with lock holder and lock expiry(maybe 1min). Set a schedule to renew lock every 30 seconds until release lock is called
