### ISSUE TITLE
Starting the migration with a particular script

### ISSUE THREAD

**Issue by amiralgazi** [lecaillon/Evolve#118]
Is there a possibility to start the migration process with a particular script?
Let's say we have 100 scripts. Can we start the migration, for example, from script No.92?
Note - changelog table contains nothing.

**Comment by lecaillon** [comment]
I think you can use `Evolve.StartVersion` as the version used as starting point. See [configuration options](https://evolve-db.netlify.com/configuration/#options) for more information.

**Comment by amiralgazi** [comment]
Thanks!
