### ISSUE TITLE
Migrating stored procedures

### ISSUE THREAD

**Issue by IndikaUdagedara** [lecaillon/Evolve#119]
Feature request
-----------------

Evolve works perfectly fine with migrating store procs e.g. Add `V123_1__ChangeSP1.sql` will alter the SP as long as the script has the appropriate `alter procedure` statement. However, __the challenge is with detecting changes during code-review/change tracking__, since `V123_1__ChangeSP1.sql` has to have the modified SP entirely and `git diff` won't be able to detect the changes.

I'm just wondering if you have any feature planned to address this.

I'd propose something like the following.

1. Have a directory for SPs e.g.
```
/StoredProcs
     SP1.sql
     SP2.sql
     ...
```

2. To migrate SP1 with new changes do the following
    1. Modify `/StoredProcs/SP1.sql`
    2. Add a migration `V123_1__ChangeSP1.sql` with **empty** content but with metadata indicating which SP got changed. This could be a SQL comment in the first line e.g.
    ```
     -- SP1.sql
    ```
    3. Evolve would parse all migration scripts as usual and when it sees the above metadata, it'll execute `/StoredProcs/SP1.sql` and add `V123_1__ChangeSP1.sql` to the migration log table. 

`2.i` will make sure the SP change is shown in `git diff`. 
`2.iii` will make sure the change is tracked along with other migrations. 
`2.ii` is the change required in Evolve.

This feature would be useful not just for SP migration but other objects that can't be altered partially e.g. DB triggers.

What are your thoughts?

**Comment by lecaillon** [comment]
Thanks for the feedback ! 
I think you can just achieve your goal with the new feature called [repeatable migration](https://evolve-db.netlify.com/concepts/#repeatable-migration)
It will allow you to run at the end, all the migrations starting with `R__` that changed since their last execution. Ideal for views and stored procedures and... code review

**Comment by lecaillon** [comment]
@IndikaUdagedara I think I can close the issue. If you have any feedback concerning your point feel free to create a new one.
