### ISSUE TITLE
Evolve Cli wrong return code

### ISSUE THREAD

**Issue by petronij** [lecaillon/Evolve#120]
I used released version 2.2.0 
and it still returns string and not 1 in case of any error

**Comment by lecaillon** [comment]
Can you be more specific ? Is this issue linked to an already closed issue ?

**Comment by petronij** [comment]
We use it in powershell  .\evolve migrate sqlserver -c "Server=$server;Database=$database;Integrated Security=SSPI;" -l $pathCommon

**Comment by lecaillon** [comment]
Can you try with the [pre 2.3 version](https://ci.appveyor.com/api/buildjobs/xwlndjk85aa9730t/artifacts/dist%2Fevolve.exe) please and tell me if it fix the issue ? Thx

**Comment by petronij** [comment]
yes it returns 1 on failure

**Comment by lecaillon** [comment]
ok, I will officially release the fix in Evolve 2.3 by the end of next week.

**Comment by petronij** [comment]
Hi ,  Is there an update on 2.3 version ?
I don’t see it there
https://github.com/lecaillon/Evolve/releases

**Comment by lecaillon** [comment]
Yes, sorry about it. A little lazy at the moment indeed ^^
I will push the version 2.3 when I will closed the issues in the current project.
Anyway all AppVeyor builds already include the fix and are stable. You can download the latest version of the CLI [there](https://ci.appveyor.com/project/lecaillon/evolve/build/artifacts)
