### ISSUE TITLE
Strange behavior when the casing of the prefix is different than specified

### ISSUE THREAD

**Issue by kippm** [lecaillon/Evolve#121]
When a file starts with a lower case v, and when the prefix specified the upper case V, an error is raised when you run a migration. "Prefix V not found in sql name:...".

For me this file should be either ignored because the prefix is not a V, or the file should be accepted as a correct file. Now it is half half. It is included in the files to be used, but excluded, because the casing is incorrect.

For me being case insensitive would be the best option. So v or V should be accepted.

**Comment by lecaillon** [comment]
Fair point. Not sure about the best option to choose. If anyone else has an opinion ?

**Comment by kippm** [comment]
I have my files in a Visual Studio SQL project, under TFS control. If I by accident use the lower case v, when I create this file, changing the file name later with a V, this is changed and visible in the project, but the file on disc still has the lower case v, which is causing an issue when doing a migrate.

**Comment by lecaillon** [comment]
Same thing with git ;)

**Comment by lecaillon** [comment]
Ok, let's make it case insensible
