### ISSUE TITLE
Error returned from the CLI are too verbose

### ISSUE THREAD

**Issue by kippm** [lecaillon/Evolve#122]
I don't really like the fact the from the CLI the dot not error stack is shown. Maybe there is a reason for it, but this is not nice when it is presented to a none developer, like a DBA, that has to run the CLI. Just the real error should be displayed.

**Comment by lecaillon** [comment]
You mean just the _root_ exception message ?

**Comment by kippm** [comment]
Yes, the root exception. The really SQL exception, not the dot net exception. It is just easier to read.
