### ISSUE TITLE
The info function should be enhanced

### ISSUE THREAD

**Issue by kippm** [lecaillon/Evolve#123]
The info function that display info, should be enhanced. I would like it to look more like the one in flyway.
- Table should not break lines.
- Show info about files before the first record in the change log.
- Show pending files.

**Comment by lecaillon** [comment]
I don't see what you mean in the first 2 points. Can you enlight me by giving me an example please

**Comment by kippm** [comment]
1) You would have to increase the width of the command window, in order to see something that looks like a table, otherwise one "record" is split over two lines.

2) If I start a migration with V2.0, but my directory also contains V1.0 files, these are not shown with the info.

**Comment by lecaillon** [comment]
And what do you want to see for migration files you left aside by specifying a `StartVersion` option ?

**Comment by kippm** [comment]
Maybe "before start".
It would also be helpful if you could show "out of order" files.

**Comment by lecaillon** [comment]
`evolve info` does not break line when the description of the migration is wide. Maybe your terminal does ?

**Comment by lecaillon** [comment]
Also based on what you proposed:
- Display "before start" ignored migration could be usefull indeed. Maybe not persisted in the metadatable.
- Display pending migrations can be tricky, but the running one, why not ? 
- Hide repeatable migrations from the output with a new option like `evolve info --hide-repeatable` ?
- Add migration elapsed time in the description of the migration (to avoid adding a new column in existing metadata tables for all RDBMS)
