### ISSUE TITLE
GetFileName in EmbeddedResourceMigrationLoader could be improved

### ISSUE THREAD

**Issue by KonFr** [lecaillon/Evolve#125]
In this case even if file name contains dots file name is returned correctly:        

        private string GetFileName(string resource)
        {
            Check.NotNullOrEmpty(resource, nameof(resource));

            if (resource.Split('.').Length < 2)
            {
                throw new EvolveConfigurationException(string.Format(InvalidEmbeddedResourceFormat, resource));
            }

            Match versionedScript = Regex.Match(resource, @"(\.v\d{1,4}_)", RegexOptions.IgnoreCase);
            if (versionedScript.Success)
            {
                return resource.Substring(versionedScript.Index + 1);
            }

            Match repeatableScript = Regex.Match(resource, @"(\.r_{2})", RegexOptions.IgnoreCase);
            if (repeatableScript.Success)
            {
                return resource.Substring(repeatableScript.Index + 1);
            }

            return string.Empty;
        }

**Comment by lecaillon** [comment]
Thanks for your proposal, but I prefer the way it is currently done.
