### ISSUE TITLE
Cannot connect to SQL SERVER server named like SERVER\INSTANCENAME

### ISSUE THREAD

**Issue by RazvanB** [lecaillon/Evolve#126]
When reading the evolve.json file the Evolve.MSBuild.CliArgsBuilder.Normalize will remove all the '\' character from the server name. 

There must be a way to allow special characters like using \\\\

**Comment by lecaillon** [comment]
@RazvanB an example of the value you want to use will help. thx

**Comment by RazvanB** [comment]
For example RAZVAN\SQLSERVER2017DEV

**Comment by lecaillon** [comment]
Changed the json parser, in Evolve 2.3 you can use `RAZVAN\\SQLSERVER2017DEV`
