### ISSUE TITLE
In-app mode not working

### ISSUE THREAD

**Issue by pumpkiiin** [lecaillon/Evolve#13]
I have an application on .NET 4.5.2, database is SQL Server 2016. MSBuild mode works just fine, but in-app mode is not working and an exception is not thrown.Here is the code I used to create the reference: 

SqlConnection conn = new SqlConnection(WebConfiguration.sqlConnectionString);
var evolve = new Evolve.Evolve(conn, msg => Console.WriteLine(msg))
{
                    Locations = new List<string> { "Migration_Scripts" },
                    Command = CommandOptions.Migrate,
                    MetadataTableName = "changelog",
                    Driver = "SqlClient",
                    SqlMigrationPrefix = "V",
                    SqlMigrationSeparator = "__",
                    SqlMigrationSuffix = ".sql",
                    PlaceholderPrefix = "${",
                    PlaceholderSuffix = "}"
};
try
{
                    evolve.Migrate();
 }
catch (Exception ex)
{
}

**Comment by lecaillon** [comment]
Hi Catalin,

I think Evolve does not find the **Migration_Scripts** folder *in-app* mode.
It works via MsBuild because the MsBuild task copy the `Locations` folders to the output folder for you. If you use Evolve directly you have 3 options: 
- Set the full path to your migration folder 
- Set the relative path to your migration folder from the output folder of your project
- Use Visual Studio on each of your .sql file and modify the `Copy to Output Directory` property to `Copy always`

Don't hesitate to give me some feedback :smiley:

**Comment by pumpkiiin** [comment]
Hi Philippe,

 Thank you for your quick response.I set the full path to the migration folder and it works.
 I don't want to use the **MsBuild** and I removed the options from **Web.config** and the application only uses the **In-app** mode.
 I've met another problem, when I add a new **.sql** file in **Migration_Scripts** I have to build the project and run the application to migrate the file, if I don't build the project the **.sql** file won't migrate.
 Is there a way to migrate the file/s without building the project after I add a file in the migrations folder?

**Comment by lecaillon** [comment]
I don't reproduce your issue. I think you are struggling with your location path. 
In your case, be sure to use the **original** Migration_Scripts  folder, not the one Evolve build task will copy in your output folder.

**Comment by pumpkiiin** [comment]
Hi,

The problem was that I wanted to migrate the sql files in **Application_Start** method from **Global.asax.cs**.I needed to restart IIS and run the application again to solve this.I didn't pay attention to this detail.
 Your migration tool is very useful and I am looking forward to use it.
 Thank you for your quick responses.
