### ISSUE TITLE
Repeatable migration, re executing old version 

### ISSUE THREAD

**Issue by CaueArua** [lecaillon/Evolve#131]
If I have the same application running on two machines and one is running an old version, all Repetitive migration will be executed, so all procedures will be outdated, is there any way to prevent this?

![errorEvolve](https://user-images.githubusercontent.com/11984240/62632835-83e24880-b909-11e9-9ce7-7360683539c8.png)

**Comment by lecaillon** [comment]
Sorry, can't see any solution to your issue.

**Comment by CaueArua** [comment]
You can ignore if any checksum matches, and set a flag to force upgrade to older version or not.

**Comment by lecaillon** [comment]
I'm not confortable with the idea. The goal of Evolve is to keep migrations simple. Add an other flag to force a repeatable migration to reapeat itself seems not obvious at first. 
All of it to ignore a migration and thus let an outdated application runs with a more recent database schema seems really risky for the overall stability. 
In my opinion, it is not the concern of Evolve to deal with outdated applications.
