### ISSUE TITLE
Evolve CLI as a dotnet global tool

### ISSUE THREAD

**Issue by IndikaUdagedara** [lecaillon/Evolve#132]
Any plans to publish Evolve CLI as a dotnet global tool ?

It was mentioned in issue #90 but can't find it as a global tool.

**Comment by lecaillon** [comment]
Good idea, thx. I will do it in the next versio of Evolve: 2.4

**Comment by lecaillon** [comment]
@IndikaUdagedara Done! I release a 2.3.0 version there: https://www.nuget.org/packages/Evolve.Tool/
Run this command to install it:
```
dotnet tool install --global Evolve.Tool
```
