### ISSUE TITLE
Improve control over repeatable migrations execution order

### ISSUE THREAD

**Issue by AndrewBoklashko** [lecaillon/Evolve#143]
Hi and thanks a lot for a great tool!

We have an application which has a lot of business logic in database as stored procedures and functions. Repeatable migrations are extremely helpful on maintaining them. The problem appears when a few dependent procedures need to be changed.

For example, let's consider these scripts R__getOrder and R__applyOrderPricing and assume that the latter uses the former to fetch order. But this will not work as is, at least in SQL Server there will be an error about missing getOrder procedure, while executing R__applyOrderPricing. Same thing if we need to change the signatures.

I am aware that there are a couple of workarounds, like:
- combine 2 scripts into single one with the correct order
- imply on ordering using synthetic prefix on migration description
- create versioned migration which adds procedures in the correct order

But any of these workarounds will negatively impact maintainability of the migrations, because I would like to keep my procedures in separate files with clean names. And why would I have to create a versioned migration in a case where it should not be needed.

My proposal is to add support for some kind of directives in migrations, to be able to imply on execution order. For example to specify this on the beginning of R__applyOrderPricing:
-- #run_after R__getOrder

Not only this solution will be much cleaner and will greatly express what we want to achieve, but it can also be a basis for some other useful features, like pre/post execute hooks.

Let me know about your thoughts on this, I am interested in submitting a PR if we agree on implementing this.

**Comment by lecaillon** [comment]
Hello, thank you for your feedback.

I'm not sure though to understand why you can not order your repeatable migrations with a number included in the name ? For example :
- R__100_getOrder
- R__110_applyOrderPricing

In my mind, add the support for some kind of directives in migrations, seems overkill for that requirement.

I would have think about directives in migration script for an issue like this one: #81
