### ISSUE TITLE
Evolve 2.3.x fails to insert migrations due to null value on installed_on

### ISSUE THREAD

**Issue by jaubin** [lecaillon/Evolve#155]
Hi,

Platform :
- .Net Core 2.2.3
- Evolve 2.3.0
- SQL Server 2012/2016

Libs : 
- System.Data.SqlClient 4.6.1
- Core.SqlServer 2.2.4

Steps to reproduce : 
DO : create a project with some migrations on Evolve 2.2
DO : run the project
DO : upgrade Evolve to version 2.3
DO : run another migration
EXPECT : migration works fine
ACTUAL : migration fails with "Cannot insert the value NULL into column 'installed_on', table changelog"

This issue is a blocker. Could you please fix it ASAP or at least provide some migration path in the documentation ?

**Comment by lecaillon** [comment]
Hi,

Below is the script of the table `changelog`. As you can see the column `installed_on` has a default value: `GETDATE()`. The insert statement does not provide any value for it, and moreover this part of the code hasn't changed between Evolve 2.2 and Evolve 2.3. 

You should check the schema of your table `changelog` and see if it matches this:

```
string sql = $"CREATE TABLE [{Schema}].[{TableName}] " +
 "( " +
	 "id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, " +
	 "type TINYINT, " +
	 "version VARCHAR(50), " +
	 "description VARCHAR(200) NOT NULL, " +
	 "name VARCHAR(300) NOT NULL, " +
	 "checksum VARCHAR(32), " +
	 "installed_by VARCHAR(100) NOT NULL, " +
	 "installed_on DATETIME NOT NULL DEFAULT GETDATE(), " +
	 "success BIT NOT NULL " +
 ")";
```
Here is the class [SQLServerMetadataTable](https://github.com/lecaillon/Evolve/blob/2.3.0/src/Evolve/Dialect/SQLServer/SQLServerMetadataTable.cs) involved in the process. You can check if you see anything that could explain your behavior, specially the method `InternalSave()`

Waiting for your feedback

**Comment by lecaillon** [comment]
Glad to hear it !
