### ISSUE TITLE
Drop MySql schema fails on dependent schemas

### ISSUE THREAD

**Issue by gitblit** [lecaillon/Evolve#157]
In the case where the database schema has evolved to be a little cross dependent (e.g. `A.Table1` has a foreign key reference to `B.Table`), you can not `DROP SCHEMA B` because it violates referential integrity.

Changing the database design is possible, but it's also possible to relax foreign key constraints on the `DROP`.  I note that foreign key constraints are relaxed on other destructive operations in the MySQL dialect.

PR is forthcoming for consideration.

- Version: 2.3
- MySQL (any version)
- .Net Core 2.2 (Windows, Linux)

**Comment by lecaillon** [comment]
Thank you @gitblit for reporting this issue and for the associated PR
