### ISSUE TITLE
Evolve Application Lock issue

### ISSUE THREAD

**Issue by muthukrishnan32** [lecaillon/Evolve#159]
Hi Team,

I'm trying to deploy my code with DBMigration enabled, but after deployment in DEV server im getting the issue in the file attached. Kindly let me know how to fix this.

![Evolve Issue](https://user-images.githubusercontent.com/48045413/73155040-68f5d180-40ff-11ea-940d-833f12862c0d.png)

**Comment by muthukrishnan32** [comment]
Im using PostgreSQL database...

**Comment by lecaillon** [comment]
Evolve uses a session level lock to coordinate the migrations on multiple nodes. This prevents two distinct Evolve executions from executing a migration on the same database at the same time.
So I see 2 reasons to the logs above: 

- either Evolve is still running
- or these are the logs of other containers you may have started ?

**Comment by lecaillon** [comment]
@muthukrishnan32 Any news ?

**Comment by muthukrishnan32** [comment]
Sorry for the late response...
Now I'm getting the same issue in Production server..
Also, the logs which you were seeing was the cloudwatch logs which I have implemented before and after evolve running...

**Comment by muthukrishnan32** [comment]
Added to the above comments, im getting this application lock issue only in DEV and production now...other environments like TEST01, AutoTest, Hardening and Staging its running fine without any issues..

**Comment by muthukrishnan32** [comment]
I'm using Evolve version 1.8.0...Could you please help me to get this resolve ??

**Comment by lecaillon** [comment]
Could you use the latest version first please ?

**Comment by muthukrishnan32** [comment]
Sure...

**Comment by lecaillon** [comment]
I re-read your first comment. And the message "Evolve cannot acquire lock" is normal when you have multiple instance of your application. As I said Evolve uses a session level lock to coordinate the migrations on multiple nodes. This prevents two distinct Evolve executions from executing a migration on the same database at the same time.
So while your migration runs in one container, the others wait the end of the migration. When it ends the lock is released and the other instance can continue.

**Comment by muthukrishnan32** [comment]
So, upgrading the version will help me to get rid of this issue ?

**Comment by lecaillon** [comment]
This is not an issue. It is the normal behavior

**Comment by muthukrishnan32** [comment]
But my scripts are not running because of this

**Comment by muthukrishnan32** [comment]
Its a kind of block...

**Comment by muthukrishnan32** [comment]
One more thing I need to inform you...As of now, we are using .NET Core project, in our service project inside that startup.cs file we have enabled the evolve dbmigration, so each and every hit from the application, this migration will get trigger. This is the right approach ??

**Comment by lecaillon** [comment]
Yes, and if Evolve is already running elsewhere it will wait before continue, displaying every 5 seconds the famous : "Evolve cannot acquire lock". This behavior is normal.

Check this [sample](https://github.com/lecaillon/Evolve/tree/master/samples/AspNetCoreSample_Evolve)

**Comment by muthukrishnan32** [comment]
sure thanks...will check it...

**Comment by muthukrishnan32** [comment]
Hi,
I have upgraded the evolve version to 2.3.0. Also, except DEV in all the other environments i dint get this error. Please find the below screenshot.

![image](https://user-images.githubusercontent.com/48045413/74556871-f1d88e00-4f84-11ea-8849-6d8791148573.png)

**Comment by lecaillon** [comment]
Sorry I have no idea. But if it works on some environments but not on others, it is due to something in the conf of your env/database I think.

**Comment by muthukrishnan32** [comment]
Hi, After upgrading the version from 1.8.0 to 2.4.0, my application and scripts are running fine in Production. Thanks :)
