### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by izep** [lecaillon/Evolve#16]
Add a command line interface to run migrations. Something similar to a wrapper around Evolve.dll, that accepts either a settings file or command line parameters. 

Similar to https://flywaydb.org/documentation/commandline/.

**Comment by lecaillon** [comment]
Good idea :thumbsup:. I'll look into it. 

I think we need 2 CLI: 
- One for the .NET framework, ideally a single .exe
- And one for the .NET Core, eventually integrated with the dotnet CLI

And we need to think about the packaging: should we use the Evolve Nuget package (I think so for now) or create an another distribution (for example Evole.CLI) ?

**Comment by sartan** [comment]
A dotnet CLI integration would be great, specifically to be able to run migrations ad hoc (as opposed to having them them run automatically post-build).

**Comment by Pvlerick** [comment]
Our preferred choice at work would be to run Evolve at deployment time, which means that we either build our own tool or use a command line.

If you don't mine, I'll investigate this a little bit as it would be the preferred option :-)

**Comment by lecaillon** [comment]
@Pvlerick Why don't use the MSBuild mode ? https://evolve-db.netlify.com/getting-started/#msbuild-mode

If you dont't want to execute Evolve during your dev let the Evolve.Command parameter empty in the evolve.json file. And set it in your CI. At the end of your build Evolve wioll then be executed automatically.

To activate this feature for Cassandra you have to update 3 classes you forget I think: `CoreDriverConnectionProvider` and `DriverConnectionProvider` and `CoreDriverConnectionProviderForNet `

**Comment by Pvlerick** [comment]
@lecaillon As far as I understood, MSBuild mode means that you do it once, at build time.

This means that if you build once but deploy many times (dev/test/prod), that model doesn't work. It also better to only have one way of doing things for all environments.

The issue we have with the in-app is that 1) all applications need to reference Evolve (which is only at tool, after all); 2) the app user needs to have elevated permissions.

Executing Evolve at deploy time solves all that.

**Comment by lecaillon** [comment]
@Pvlerick Waiting for your proposal ;)

**Comment by Pvlerick** [comment]
@lecaillon @izep @sartan 

Here is an early draft: https://github.com/Pvlerick/Evolve/tree/issue-16-add-command-line-interface

Basically, it would work like this:
```evolve <engine> <connection-string> [options]```

So, you could do 
```evolve mysql "Server=127.0.0.1;Port=3306;Database=my_database;Uid=root;Pwd=Password12!;" --location "C:\scripts\" --timeout 30``` 
Or, abreviated (thanks to https://github.com/commandlineparser/commandline):
```evolve mysql "Server=127.0.0.1;Port=3306;Database=my_database;Uid=root;Pwd=Password12!;" -l "C:\scripts\" -t 30``` 

Now, this is for the standalone .exe that I will try to generate using something like il-repack. We could also distribute the tool using the new ```dotnet install tool -g <package>``` but I'll worry about that later.

Let me know what you think!

**Comment by lecaillon** [comment]
- Evolve command should appear clearly: ```evolve <command> <engine> <connection-string> [options]```

The packaging part is quite vague for me at the time:
- Do we have to embed all the database drivers in the CLI ?
- Do we have one CLI for .NET and an other for .NET Core ?

I don't know that much il-repack. Not sure we can have a single .NET Core app (a la GO) without the need to have the framework installed on the machine. 

@Pvlerick Great intiative by the way !

**Comment by Pvlerick** [comment]
I will move toward something like ```evolve cassandra migrate ...``` which is much easier to handle with the ```CommandLineParser``` library. If we want to reverse it to ```evolve migrate cassandra ...``` at the end of this work, we can do it but it'll mean more code. We'll see, it's not a hard or blocking task anyway.

For the packaging, my idea would be to generate a single .exe file if possible, such as NuGet (not sure if the .NET fw would be required on the machine still...), but also to offer a package that can used with the ```dotnet``` command. We'll need to embed all the database drivers in this, I'm afraid - I fail to see a way to avoid this. But since this is not in the application and is run separately (at deploy time, ideally) I don't think that's a big issue if the .exe is a little bit bloated.

**Comment by Pvlerick** [comment]
Here is the current version: https://github.com/Pvlerick/Evolve/tree/issue-16-add-command-line-interface

It should work will all drivers now. It is a bit rough around the edges (wrong parameter values will quickly get you a stack trace in the stdout) but it works for what I have tested - admittedly, only Cassandra ;-)

At the moment, this is netcoreapp2.0 only; support for the full the framework should be added at some point, but this is a starting point.

**Comment by Pvlerick** [comment]
Ok, the CLI is now multi target: net452, netcoreapp1.1 and netcoreapp2.0; that was easier than I thought :-)

I'll look into the packaging options.

**Comment by Pvlerick** [comment]
@antgel sorry for the late reply, I have been offline for the most part of the month :-)

There is [a branch for this in my fork of Evolve](https://github.com/pvlerick/Evolve/tree/issue-16-add-command-line-interface). It all works fine, but for the moment the generated tool carries all the drivers. As discussed here, we'd like this to go and specify the driver as on of the argument to the command line.

Other than this, the tool works. In only tested it in "production" (meaning in dev at work) for Cassandra, but it does the job (it was added to our deployment scripts that are run by Octopus).

**Comment by antgel** [comment]
@Pvlerick Sounds like a good month. ;) Thanks for the update. We are still polishing our CI implementation, but will get to it soon, and we'll need to decide how to proceed. What will it take to get this polished and merged upstream? Specifying the driver doesn't sound like a big task (disclaimer: I'm aware it's not my time).

**Comment by Pvlerick** [comment]
@antgel No, specifying the driver shouldn't be a big task, but some rework needs to be done in the parameters to the CLI since for some drivers you might want to have special parameters.

I should be able to have a bit more time to look at this at the end of the week and as of next week :-)

**Comment by lecaillon** [comment]
Not much time for the moment either. But the release of the .NET Core 2.1 could be the occasion to have fun with the new .NET Core Tools :)

**Comment by lecaillon** [comment]
Finally starting the CLI. As expected, the db driver part is a bit tricky:

### Option1

We use the driver assemblies of the targeted application (somehow like the Evolve MSBuild task is actually working). Below a *working on my machine example* of an app, targeted .NET Core: 
```
evolve.cli postgresql erase "Server=127.0.0.1;Port=5432;Database=my_database;User Id=postgres;Password=Password12!;" --enable-erase=true --depsFile="C:\Users\Phil-Dev\Evolve\test-package\Evolve.Npgsql.AspNetCore11.Test\bin\Release\netcoreapp1.1\Evolve.Npgsql.AspNetCore11.Test.deps.json" --nuget-package-dir="C:\Users\Phil-Dev\.nuget\packages"
```
Pay attention at the "2 not so obious args" **depsFile** and **nuget-package-dir** at the end ... Normally I inferred them at build time from MSBuild, but in this case I see no option but to require them in the command line args.

### Option2
We embed the drivers assemblies in the CLI. This way we can use Evolve.CLI alone, without any targeted application. I didn't tested it, but I can see the drawback will be the package size and also the number of combinaison (.NET fwks / driver type) we would have to support.

So the most important question: **How did you imagine this feature at first ? Option 1, Option 2 or something else ?**

**Comment by antgel** [comment]
@lecaillon @Pvlerick Any updates on this? :)

**Comment by lecaillon** [comment]
@antgel work in progress :)

**Comment by lecaillon** [comment]
@antgel @izep @sartan @Pvlerick @Sacrelicious 

A very alpha version of the Evolve CLI for .NET projects is available [here](https://ci.appveyor.com/api/buildjobs/97uadjy0k6i6hkbm/artifacts/dist%2FEvolve.exe).

#### Help:
`Evolve.exe --help`

#### Usage:
`Evolve.exe postgresql erase -c "Server=127.0.0.1;Port=5432;Database=my_database;User Id=postgres;Password=Password12!" -p C:\projets\Evolve\test\Evolve.IntegrationTest.PostgreSQL\bin\Debug -l Resources/Sql_Scripts/Migration --schemas public unittest -s unittest --placeholders schema1:unittest`

Feel free to try it and to give some feedback. 
Before a new release (1.9.0), have to write some tests yet and implement the .NET Core version too.

**Comment by lecaillon** [comment]
A full new standalone CLI will be relased alongside the Evolve 2.0.0 version
