### ISSUE TITLE
Clarify documentation around passing arguments via response file to the CLI

### ISSUE THREAD

**Issue by Supratentorial** [lecaillon/Evolve#172]
Hi,

I just had a suggestion around documentation around the CLI, specifically with regards to passing a response file.

If possible, under the [Examples](https://evolve-db.netlify.com/cli/#examples) subheading could we label the contents of the args.txt file to make it explicit.

Just adding a simple "Contents of args.txt:" I feel would be helpful.

Thanks

**Comment by lecaillon** [comment]
Done
