### ISSUE TITLE
Let Evolve migrate against flyway schema history table

### ISSUE THREAD

**Issue by honzakuzel1989** [lecaillon/Evolve#174]
Hi,

I know that Evolve is only inspired by Flyway but some times there is need to migration against flyway schema history table (`flyway_schema_history`). 

The table has almost the same structure like evolve `chanelog` only with small diferencies (e.g. checksum). It would be nice in Evolve especcialy in large systems with several technologies (like java+flyway and dotnet+evolve) when you have to cooperate and work on same datastore.

WDYT ?

**Comment by lecaillon** [comment]
LOL, never thought about this. Interesting though, but coupled Evolve to the table definition of another lib does not seem such a good idea. And the use case where several application could use the same database seems also like an anti pattern anyway. We should certainly stay inspired by Flyway and not go to far. But thanks for the idea @honzakuzel1989

**Comment by honzakuzel1989** [comment]
It is really so funny idea? :) You said coupled. I did not thinking about coupling! I thought about posibility (e.g. through configuration). Something ling migration policy or migration table schema.

As I said. The `changelog` table is almost the same like in `flyway`. Only `checksum` is different but known. Why did you use a different table? Just asking.

But I agree with you about  use case when several application use same data storage. It is not very good solution and in some architectures is it antipatern. 

But applications live in real world and when it happends they need a synchronization.

**Comment by lecaillon** [comment]
When I said coupled, I mean I do not think to share the same schema that flyway is a good idea. If they decide to change anything, it will break evolve. More over it would'nt be the only change to do. To ensure that multiple migrations cannot appened at the same time, we have a locking mecanism that should be synchronized between the 2 lib, the computed checksum too ... 
Maintain and test this kind of dev is to much effort. Few people concerned by the use case you discribe, should use Flyway or Evolve by the way, all along. I remind you Evolve has a cross platform CLI tat could be used in all env. Not only .NET ones

**Comment by honzakuzel1989** [comment]
Ok, I understand. Thank You for answers.
