### ISSUE TITLE
validation flag to check the scripts executions

### ISSUE THREAD

**Issue by upolishetty** [lecaillon/Evolve#175]
With the present scenario, the pending script will be executed sequentially and rollbacks only the failure script for any failures. 

For production cases, it's not recommended to apply half of the changes in a DB. It's better to run all the scripts in validation mode once and check for any failures.

Added PR that contains an additional flag to run in validation mode.

https://github.com/lecaillon/Evolve/pull/173

**Comment by lecaillon** [comment]
Hi, thanks for pointing out the Azure DevOps CI pipeline was failing. The agent image used does not install MySql by default anymore. Fixed.
For your proposition, I'm not sure this feature is a good idea. 
First I hope the database migrations are not tested directly in production. So the use case you discribe should be very rare. 
More over it is recommanded to maintain backwards compatibility between the DB and all versions of the code currently deployed in production. So have them half installed shouldn't be an issue either. And if two database modifications are linked, put them in the same script. 
Finally all databases do not support DDL transaction. For example a `CREATE TABLE` in MySQL or CockroachDB can not be rollback.

**Comment by upolishetty** [comment]
Hi,

Thanks for fixing the pipeline failure! 
I accept that MySQL or Cockroach can not rollback, for both of these, we can mark override the flag value to false.
With the existing structure, For a DDL transaction failure will it rollback for Mysql or cockroach? 

Also, the database migrations are not directly executed on the production. There might be a chance( not 100%) that script execution might fail.

Ex: If we are adding a constraint to an existing table it may fail in prod as there will a data diff from prod to local. We faced such kind of issues in real-time so expecting such flag based execution. 

It would be really helpful for our team with such implementation.

**Comment by upolishetty** [comment]
@lecaillon  Is there any update related to this?

**Comment by awoods187** [comment]
PM at CockroachDB here. We recommend not running DDL inside transactions to avoid these complications. We also encourage migration tools to add retry loops throughout their code to account for retries from our serializable isolation mode as well as those caused from distributed nodes

**Comment by mbogi** [comment]
I agree with @awoods187  and what I would recommend is to have a validation flag to test the complete sql files in a transaction. And its users call on whether to use it or not.

Let me know if you want us to make changes and raise pull request, we can do that.

Thanks,
-Mahender

**Comment by lecaillon** [comment]
Finally addressed in #210
