### ISSUE TITLE
Can there be one changelog metadata table per schema?

### ISSUE THREAD

**Issue by danhaywood** [lecaillon/Evolve#176]
Thanks for this project ... as a happy flyway user, I'm hopeful this will scratch the same itch for .NET apps.

I see that - like flyway - a single changelog metadata table can be used to service multiple schemas.

But flyway also has the ability for mulitple changelog metadata tables, one per schema, in other words each independent of the next.

Is this a feature that evolve also supports?

Many thanks
Dan

**Comment by danhaywood** [comment]
To answer my own question, yes, seems that evolve works exactly the same way as flyway here.  

* there can either be one changelog for multiple schemas, or
* one changelog per schema
* something in between, eg one changelog for several related schemas, another changelog for other distinct schema(s).

**Comment by lecaillon** [comment]
You're right, then you have to use the option: `Evolve.MetadataTableSchema` to distinct the location of the metadata table between your migrations.
