### ISSUE TITLE
Provide configuration via environment variables

### ISSUE THREAD

**Issue by sartan** [lecaillon/Evolve#18]
Current configuration techniques (App.config / Web.config / evolve.json) have you hardcode connection string into a file that will likely be committed to source control. This is not desirable since the connection string contains credentials. It would be great to be able to provide certain configuration via environment variables, for example:

```bash
DB_USER=my-user DB_PASSWORD=password dotnet build
```

This can be achieved programmatically using _in-app_ mode, but it would be nice to have this option for other modes.

Alternatively, a [CLI](https://github.com/lecaillon/Evolve/issues/16) that accepts connection string parameters would also meet this need.

**Comment by lecaillon** [comment]
@sartan Here are examples of Evolve configuration options with environment variables support:
``` js
{
  "Evolve.ConnectionString": "Server=${HOST};Port=5432;Database=myDataBase;User Id=${DB_USER};Password=${DB_PWD};"
}
```
or
``` xml
<add key="Evolve.ConnectionString" value="Server=${HOST};Port=5432;Database=myDataBase;User Id=${DB_USER};Password=${DB_PWD};" />
```

**Comment by sartan** [comment]
Thank you! Look forward to trying it out.
