### ISSUE TITLE
Flyway metadata compatibility

### ISSUE THREAD

**Issue by b-twis** [lecaillon/Evolve#181]
Hi,

We are currently using flyway for file based migration and are interested in adding some functionality to use Evolve to trigger  the migrations and stay compatible with flayway. 

Only blocker we see at the moment is the difference in metadata table structure. 

Would it be possible to add a functionality to have a flyway compatible change table?

Thanks,

Basil

**Comment by lecaillon** [comment]
Hi, thanks for the feedback. We do not planned to add that feature. See #174

**Comment by b-twis** [comment]
Sorry I didnt see that isseue before, obviously my search skills were not great yesterday.

Our use-case is a little different as we have a devops process that deploys database migrations in a controlled manner, but would also like the ability to trigger the initial migrations at runtime between devops releases on a new database.

Getting flyway into dotnet code it not a very nice thought, and Evolve does not have a Devops Marketplace task that can be installed to the pipelines to possibly replace flyway. 
So I thought that allowing for compatibility of the tables could be the cleanest approach. 

If you are not planning to add the feature, would you be interested in providing a few pointers to where I might need to change to implement this in a fork. 

So far I found
* MigrationScript (for checksum changes)
* MetaDataTable & SQLServerMetadataTable for schema and query changes

Thanks,
Basil
