### ISSUE TITLE
Can't accept duplicate filenames in different directories

### ISSUE THREAD

**Issue by richsage** [lecaillon/Evolve#183]
.NET Core 3.1 app, using the `Evolve.Migrate()` method call.

Our lookup path folder looks like this:

```
DB/
    Migrations/
        ... (this is table creation and similar)
    Repeatable/
        Schema1/
            R__vwMyView.sql
        Schema2/
            R__vwMyView.sql
```

When we run the app, Evolve throws an exception as we have 2 migrations with the same filename, even though they're in different folders (and on different schemas). It would be useful to be able to have this kind of nesting of similarly-named files with some kind of inclusion of the folder path in any lookup etc.

**Comment by lecaillon** [comment]
Migration name must be unique. It is at Evolve core. Changing that could lead to unwanted edge case for very little gain I think.
If it is an issue for you, you could prefix or suffix your repeatable scripts with the name of the schema, couldn't you ?
