### ISSUE TITLE
Repair and OutOfOrder cannot work together

### ISSUE THREAD

**Issue by Lindvorn** [lecaillon/Evolve#184]
Hello. 
I'm trying to use option OutOfOrder but in our code we also do the repair before migrate.

`var evolve = new Evolve.Evolve(cnn, msg => _logger.LogDebug($"{dbName}: {msg}"))
                        {
                             ...
                            OutOfOrder = opts.OutOfOrder
                        };
                        if (opts.RepairChecksums)
                        {
                            evolve.Repair();
                        }
                        evolve.Migrate();
`
DB has already applied migrations from ver 1.0.0 to 1.50.0 with some numbers missing. When I'm adding not applied migration 
1.2.1 the evolve.Repair() throws validation error. But I was hoping that if turn OutOfOrder then this migration is either skipped or migrated when Repair is called. If I skip evolve.Repair and run evolve.Migrate immediately then it works fine with OutOfOrder option.
Can you suggest something? 
Thank you in advance.

**Comment by lecaillon** [comment]
Hi,
Don't use `Repair` if the content of your migration file hasn't changed.
`OutOfOrder` is needed when you want to apply a migration where the version is lesser than the last one. Your case, if I understand.
Indeed those 2 options cannot work together.
