### ISSUE TITLE
MSBuild migration hangs indefinitely after upgrading to 2.4

### ISSUE THREAD

**Issue by xr280xr** [lecaillon/Evolve#185]
I've been using Evolve for a few years in a project that now has a little over 100 migration scripts. Yesterday I needed to start my database over from scratch and run through all of the migrations on it. The last script contained a large amount of inserts so I needed the timeout config added in 1.8, so I just upgraded from v1.5 to the latest v2.4 and the accompanying MS Build package. But 2.4 was unable to successfully run all of my migrations. This is in Visual Studio 2017 in a .NET Framework 4.8 class library project against a local SQL Server 2016 instance.

Build 1: changelog shows it successfully gets through my v1_65__migration.sql script but then the build seems to hang. The visual studio building animated icon in the status bar continues, the output window shows nothing new. I waited on this probably around 40 minutes before trying to cancel the build. Cancelling doesn't work. I have to kill the Visual Studio process to stop it.

Build 2: After opening the project back up, I tried to build again to just pick up where it left off. This time it ran the script instead of hanging, but had another interesting error when it got to v1_67. In v1_66, a local temp table is declared and never dropped. v1_67 declares a temp table with the same name and the error was that the temp table already exists. So it seems something changed that is executing the migrations in the same SQL session? Wondering if this change is somehow related to the hanging. 

I later started over and followed the Build 1 steps again but with SQL profiler running and observed that my v1_66_migration.sql does not get executed so it seems to be getting stuck somewhere between updating changelog for v1_65 and executing v1_66. I think the big clue is it worked with Evolve 1.5 and I've now downgraded to 1.8 and it works without problems all the way through v1_128 (although I did leave in a line to drop the temp table so I don't know if 1.8 runs into that issue or not). 

The only thing "special" I can identify about my 66 script is it's the first one to use a temp table up till that point. Everything else has been done more than once before in previous migrations. I've attached the three scripts mentioned but given that Build 2 was able to run it, it seems likely its something about the state of the SQL session or Evolve from more than just the one previous script. Hoping there is enough information to speculate what might be happening without a fully reproducible example because I'm not sure if I can share the whole thing.

[migrations.zip](https://github.com/lecaillon/Evolve/files/5531543/migrations.zip)

**Comment by lecaillon** [comment]
Hi,
Thank you to have taken the time to write a clear description of your issue.
Nevertheless hard to guess what is happening :)

I am a bit rusted with SQL Server, but why do you put the batch delimiter `GO` everywhere in your V1_66 script ?
Is it really usefull in your case ? :)
I ask the question because in Evolve the `GO` keyword is used [here ](https://github.com/lecaillon/Evolve/blob/master/src/Evolve/Dialect/SQLServer/SQLServerStatementBuilder.cs) to split your migration file into multiple statements, each one of them, executed in a the same transaction though. But it might be worth trying to remove them if possible. I suspect it could be the part that has changed between the v1.5 and following.

**Comment by lecaillon** [comment]
Since Evolve MSBuild 2.4 support is dropped, I guess this issue is no more relevant.
