### ISSUE TITLE
Skip repeatable migrations with errors

### ISSUE THREAD

**Issue by pinx** [lecaillon/Evolve#187]
This subject has been raised before: sometimes create-view scripts fail, because the referenced view does not exist, yet.

Flyway has the option to continue on errors. That would be a solution. The user could repeat the whole migration a few times, until all views are created successfully.

Another option would be to repeatedly execute scripts for as long as the number of errors decreases.

**Comment by lecaillon** [comment]
Hi, in your example, re-named your repeatable migration scripts would not correct the issue of the view that needs a non yet created view ?

**Comment by pinx** [comment]
We have a lot of views in our database, with multiple layers of dependency. When they were created, years ago, the naming was logical, but not with migration in mind.  
They are in a production database, and I scripted them with SQL Server management studio. If I have to analyze them all, and rename them, I am taking over the maintenance from the consultant. I would rather not do that, but leave the naming up to him.  
My responsibility would be to incorporate the scripts in source control and make them distributable. Currently, I can not do that with evolve.

**Comment by lecaillon** [comment]
I see your point. Is there any reason to not retry automatically the execution of repeatable migrations until the overall error count remains the same ? In other words, should this "new behaviour" be activated by default or not ? What is your opinion ? For my point of view, no. It could be the default (the only?) behaviour, even if it is considering a "breaking change".

**Comment by pinx** [comment]
I checked the documentation of Flyway on [errorOverrides](https://flywaydb.org/documentation/concepts/erroroverrides).  
This seems a bit complicated for our use case, so my proposal would be to create something similar, but simpler.  
The configuration would be 
`errorOverrides=skip|retry`  
Command line option: `--error-overrides=skip|retry`

The desired behaviour would be to skip any scripts that generate errors, and retry them if so configured.  
If we later want to have more control, we could extend towards the Flyway implementation, and e.g. skip lower error codes and still fail on more serious errors.

**Comment by lecaillon** [comment]
I'm not comfortable with the option to skip **versionned migration** in error. I do not think it is a good idea (at best a niche feature). The state of a database should be predictable after Evolve runs those **versionned migrations**.
However automatically execute **repeatable migrations** for as long as the number of errors decreases, seems a good idea to facilitate the naming of the scripts, without I think, any compromise.

**Comment by pinx** [comment]
I totally agree that versioned migrations are too important to allow them to fail.  
I do think it's good to have a switch like I described.
