### ISSUE TITLE
Repeatable migrations order

### ISSUE THREAD

**Issue by nicumaxian** [lecaillon/Evolve#188]
Is there a possibility to mark a specific migration to run "Before" a regular migrations?

Usecase:
- We have set of functions which are used in multiple other regular migrations. 
- We want to keep in all functions in one place and defining them with `CREATE OR REPLACE FUNCTION`. In this way, we easily track history with GIT
- Migration should run always, but `Before` other migrations.

Currently "Repeatable" migration doesn't fit our requirements. 
1. it runs only after regular migration
2. it runs only on checksum change

**Comment by lecaillon** [comment]
There is no dedicated option to achieve what you want.
But each time you need to add a new view, you could add it as a regular versionned migration AND as a repeatable one. Same script in the 2 files. And then of course, only update the repeatable one.

**Comment by nicumaxian** [comment]
> There is no dedicated option to achieve what you want.
> But each time you need to add a new view, you could add it as a regular versionned migration AND as a repeatable one. Same script in the 2 files. And then of course, only update the repeatable one.

Is there a chance to add feature to run repeatable migrations before regular migration?

**Comment by ssoloshchak** [comment]
There is opened PR for this: https://github.com/lecaillon/Evolve/pull/177/commits

**Comment by ssoloshchak** [comment]
> > There is no dedicated option to achieve what you want.
> > But each time you need to add a new view, you could add it as a regular versionned migration AND as a repeatable one. Same script in the 2 files. And then of course, only update the repeatable one.
> 
> Is there a chance to add feature to run repeatable migrations before regular migration?

There is opened PR to be able run repeatable migrations before regular: https://github.com/lecaillon/Evolve/pull/177/commits

**Comment by ssoloshchak** [comment]
> There is no dedicated option to achieve what you want.
> But each time you need to add a new view, you could add it as a regular versionned migration AND as a repeatable one. Same script in the 2 files. And then of course, only update the repeatable one.

There is opened PR to be able run repeatable migrations before regular: https://github.com/lecaillon/Evolve/pull/177/commits

**Comment by lecaillon** [comment]
> Is there a chance to add feature to run repeatable migrations before regular migration?

It is not planned. Execute repeatable migrations before versioned ones does not seem to be a widely shared usecase.
In order to keep Evolve simple I prefer not to consider such a feature. 

And I thought of an other workaround for your issue : run Evolve 2 times :
- First time with the[ **Locations**](https://evolve-db.netlify.app/configuration/#options) option pointed only to your repeatable migration folder : Sql_Scripts/Repeatable for example
- Second time without this options specified. It will execute this time all migration scripts.

What do you think @nicumaxian ?

**Comment by lecaillon** [comment]
Without any news from the author I close the issue. Feel free to open a new one, if you need it again
