### ISSUE TITLE
Add MySQL / MariaDB support

### ISSUE THREAD

**Issue by lecaillon** [lecaillon/Evolve#2]

**Comment by robvanpamel** [comment]
Hi, 

Is there already some progress on this one ? 

Kind regards
  Rob

**Comment by lecaillon** [comment]
I'm working on it. I hope I can find more time to release something soon. This feature is definitely wanted.

**Comment by lecaillon** [comment]
@robvanpamel 
Hi, if you like Evolve or... not , feedback would be appreciated. Evolve is young and certainly  perfectible. 
Thanks
