### ISSUE TITLE
How to fix out of order migrations that were applied to production in release branch?

### ISSUE THREAD

**Issue by shinderahulb** [lecaillon/Evolve#20]
I am working in Release branch. Main line has higher version of migration scripts. I have applied the hotfix to Production from Release branch. Now, how to apply the lower version migration in DEV environment. In flyway there was way to apply missing migration using OutOfOrder property. I am missing that property.

**Comment by lecaillon** [comment]
There is no such an option.
You could obviously run your script manually and insert a new record in the Evolve `changelog` metadata table. _(Run this hotfix in a test database first, and check the content of the metadatable)_

I'm planning to add this option in the next release of Evolve. If you could wait... but I imagine not.

**Comment by shinderahulb** [comment]
Thank you, Philippe!

Sent from my iPhone

On Nov 8, 2017, at 12:07 PM, Philippe Lécaillon <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #20<https://github.com/lecaillon/Evolve/issues/20>.
