### ISSUE TITLE
PostgreSQL 10: Validation of the database connection failed. Exception while reading from stream

### ISSUE THREAD

**Issue by ZOXEXIVO** [lecaillon/Evolve#21]
Initial migration for Postgresql failed
v1.6.0 - v1.7.0
PostgreSQL 10
.NET Core 2.0
Install clean postgresql server 10.0 and try make initial migration with simple queries.
Same code works with Postgresql 9.6

{Evolve.EvolveException: Validation of the database connection failed. Exception while reading from stream ---> Npgsql.NpgsqlException: Exception while reading from stream ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Npgsql.ReadBuffer.<Ensure>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at Npgsql.ReadBuffer.<Ensure>d__27.MoveNext()

**Comment by lecaillon** [comment]
Please... more info

Before logging a new issue, please have a quick read through the [contribution guidlines](https://github.com/lecaillon/Evolve/blob/master/CONTRIBUTING.md).

**Comment by ZOXEXIVO** [comment]
Npgsql related error

**Comment by lecaillon** [comment]
What do you mean by "Npgsql related error" ?

**Comment by lecaillon** [comment]
Can I close the issue ?

**Comment by ZOXEXIVO** [comment]
Yes
