### ISSUE TITLE
Consider changing build message for in-app mode

### ISSUE THREAD

**Issue by zimmi** [lecaillon/Evolve#22]
Hi, I'm using Evolve 1.7.0 with .NET Core 2.0 in in-app mode.
As such, I'm not using an Evolve.json file.

Being new to .NET (and NuGet), the message that gets logged when the Evolve.json file is not found (introduced in #14) was kind of misleading to me:
_Evolve.json configuration file not found. MsBuild task execution cancelled._

I read this as: My whole build didn't execute because this file was mising. I know now that this is not what's happening, but it took me a while.

I would suggest inverting the logic of that message condition and log something like:
_Evolve.json configuration file found, executing migrations._
and just do (and log) nothing when no Evolve.json file was found.

What do you think?

**Comment by lecaillon** [comment]
Hi,
This message acts as a trace when Evolve does not run at build time. 
Something like, *everything is ok, you just don't want Evolve to start at build time*.
So what about this one ?

> No evolve.json configuration file found. Evolve MSBuild task execution deactivated.

**Comment by zimmi** [comment]
That's also good, thanks!

**Comment by lecaillon** [comment]
@zimmi Changed my mind again ;)

> Evolve MSBuild mode is off: no configuration file found.

**Comment by zimmi** [comment]
Haha, writing good error messages is at least as hard as naming things. :+1:
