### ISSUE TITLE
PostgreSQL "syntax error at or near "LIKE" at character 16"

### ISSUE THREAD

**Issue by jyriaganitsh** [lecaillon/Evolve#225]
Evolve 3.0.0
Npsql 5.0.4

In db log:

```
ERROR:  syntax error at or near "LIKE" at character 16
STATEMENT:  SHOW VARIABLES LIKE '%version%'
```

**Comment by lecaillon** [comment]
It is normal. It is the way Evolve knows what kind of database is running against. Details [here](https://github.com/lecaillon/Evolve/blob/e20d448c851b5c88527b203b062fc67db1484419/src/Evolve/Extensions/WrappedConnectionEx.cs#L21) if you're interrested

**Comment by xperiandri** [comment]
Can't it be done without the exception?

**Comment by lecaillon** [comment]
Yes, you can use the last alpha version and the new optional parmeter in the constructor called [dbms](https://github.com/lecaillon/Evolve/blob/4c0c21acf814438de79ce980d5680800f02b59fb/src/Evolve/Evolve.cs#L37)

**Comment by andrii-berestov-lula** [comment]
Hi @lecaillon. This issue is still reproduced with `3.1.0-alpha7` for us. The error message is the same, as below
```
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "LIKE"

POSITION: 16
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|228_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
  Exception data:
    Severity: ERROR
    SqlState: 42601
    MessageText: syntax error at or near "LIKE"
    Position: 16
    File: scan.l
    Line: 1188
    Routine: scanner_yyerror
```

**Comment by xperiandri** [comment]
> Yes, you can use the last alpha version and the new optional parmeter in the constructor called [dbms](https://github.com/lecaillon/Evolve/blob/4c0c21acf814438de79ce980d5680800f02b59fb/src/Evolve/Evolve.cs#L37)

We still catch an exception. Were not you managed to fix that?

**Comment by lecaillon** [comment]
yes. how do you instantiate Evolve ? Can you give me more insight please
