### ISSUE TITLE
Can't specify custom table name

### ISSUE THREAD

**Issue by kellielellie1** [lecaillon/Evolve#229]
Evolve 2.4.0
Does not create custom table name - still creates 'changelog'. I have tried setting the option MetadataTableName on it's own, and I have also tried adding the MetadataTableSchema as well, in case it helps - but it doesn't.

Using MySQL

```
                var dbstring = Configuration.GetConnectionString("DatabaseConnectionString");
                var cnx = new MySqlConnection(dbstring);

                var evolve = new Evolve.Evolve(cnx, msg => Logger.LogInformation(msg))
                {
                    Command = Evolve.Configuration.CommandOptions.Info,
                    IsEraseDisabled = true,
                    EmbeddedResourceAssemblies = new[] { typeof(DataLayer.Data.Context).Assembly },
                    // This custom naming does not work! Always creates "changelog"
                    //MetadataTableName = "SchemaChanges",
                    //MetadataTableSchema = "farm_mapping.csfarmsolutions.com.au"
                };

                evolve.Migrate();
```

**Comment by lecaillon** [comment]
Using `Info` command does not alter anything in your database schema. It is normal.

**Comment by kellielellie1** [comment]
> Using `Info` command does not alter anything in your database schema. It is normal.

Took info command away, still does not create my custom table specified:

```
                var dbstring = Configuration.GetConnectionString("DatabaseConnectionString");
                var cnx = new MySqlConnection(dbstring);

                var evolve = new Evolve.Evolve(cnx)
                {
                    IsEraseDisabled = true,
                    EmbeddedResourceAssemblies = new[] { typeof(DataLayer.Data.Context).Assembly },
                    // This custom naming does not work! Always creates "changelog"
                    MetadataTableName = "SchemaChanges"
                };

                evolve.Migrate();
```

**Comment by lecaillon** [comment]
You use the wrong Evolve package. See my comment [here](https://github.com/lecaillon/Evolve/issues/230#issuecomment-843682251)

**Comment by kellielellie1** [comment]
> You use the wrong Evolve package. See my comment [here](https://github.com/lecaillon/Evolve/issues/230#issuecomment-843682251)
> Use this [package ](https://www.nuget.org/packages/Evolve) instead

Thanks, I was wondering why evolve was running during build, I had taken this task over from another dev and dint realise the msbuild version was also installed. Shall I delete these two issues from your board?

**Comment by lecaillon** [comment]
No, I'm just gonna close them. See you !
