### ISSUE TITLE
How to Use afterMigrate__ or call back in evolve ??

### ISSUE THREAD

**Issue by maulikhdave9601672767** [lecaillon/Evolve#238]
How to Use afterMigrate__ or call back in evolve ??
my issue is i want use sql call back after each migrate 
please let me know how i can use it?
i want to use my own afterMigrate__permission.sql call back  how can i use it

**Comment by lecaillon** [comment]
Currently there is no callback in Evolve. But you can create a repeatable migration with the new instruction `-- evolve-repeat-always` in the content of the migration using `Evolve 3.1.0-alpha1`
This way at the end of each Evolve execution your repeatable migration will be exeecuted even if its hash hasn’ t changed.

**Comment by maulikhdave9601672767** [comment]
ok thank you
