### ISSUE TITLE
Increase Command Timeout

### ISSUE THREAD

**Issue by xr280xr** [lecaillon/Evolve#25]
I don't know if this is just not an intended use for migration files, but I'm trying to seed postal code data in a migration. To me it makes sense because it is a default set of data that my my application will need in order to run and the table is meaningless without its data. Since it is tens of thousands of rows to insert, it takes a while to complete and Evolve's command is timing out. We tried breaking it up into smaller batches using "GO" (this is SQL Server 2016), but it still times out. Maybe we just didn't go small enough on the batches (they only take about 12 seconds to execute individually in SSMS) but is there a way to configure the command timeout?

**Comment by lecaillon** [comment]
Evolve use the default [command timeout](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.commandtimeout(v=vs.110).aspx) that is 30 seconds.
And there is currently no way to change that. I could later add a configuration property. 

Then Evolve [splits your migration script](https://github.com/lecaillon/Evolve/blob/609e5b1ad0158f5a745ca3e7269cb9fae3be05b7/src/Evolve/Evolve.cs#L450) following database batch delimiter (GO for SqlServer) to avoid several edge cases. The transaction is committed only when the **whole** sql file has run successfully.

So in your case, added GO statements did not change anything for Evolve. For now, I only see one solution: split your script in x several sql scripts with the drawbacks it implies.

**Comment by lecaillon** [comment]
In Evolve **1.8.0**, added a new optional configuration parameter: `Evolve.CommandTimeout` to set the wait time before terminating the attempt to execute a migration and generating an error. (The default is 30 seconds.)
