### ISSUE TITLE
Microsoft.Data.SqlClient package

### ISSUE THREAD

**Issue by JayDZimmerman** [lecaillon/Evolve#265]
Has investigation been done into using the new "Microsoft.Data.SqlClient" package instead of "System.Data.SqlClient"?  Microsoft has stated that it is the ultimate successor and functionally equivalent  My interest lies in the fact that it also brings additional Azure Active Directory authentication options with it.

**Comment by lecaillon** [comment]
Yes i tried. But at the time (6 months ago i would say) it didn't support well the trimming phase i use to shrink the size of Evolve .NET Tool or Evolve CLI. In other word it didn't work. 
You can use Evolve in your code. Doing this it is you that gives a `DbConnection` to Evolve and so, you can use any database driver you want

**Comment by JayDZimmerman** [comment]
Appreciate the response.  I was planning on using the .NET Tool or CLI rather than the library; however, it appears simple enough to customize the source of one of those to meet my needs.  Thanks for the insight.

Though it might muddy the implementation, one helpful enhancement would be the ability to pass an access token to the Tool/CLI, which could then be attached to the SqlConnection.  This would provide an option for those of us using Azure Active Directory to leverage the existing product with the use of "System.Data.SqlClient".  In fact, that may be my first try before heading down the "Microsoft.Data.SqlClient" path.

**Comment by lecaillon** [comment]
see #267
