### ISSUE TITLE
MSBuild task fails if path contains parentheses

### ISSUE THREAD

**Issue by Lindvorn** [lecaillon/Evolve#28]
Greetings!
First of all I want to thank you for this cool project.

In my project I use Evolve v.1.7.0 for net.core and net451, Jenkins to build the application.
Problem occurs when path to the project contains "(" or ")".
[Here ](https://connect.microsoft.com/VisualStudio/feedback/details/713690/msbuild-4-0-usingtask-cannot-have-a-path-with-parentheses) is the error reported to msBuild.
Seems like build file "Evolve.targets" miss the fix suggested by MS team.
Can you, please, fix Evolve.targets so it can be used with projects where parentheses are present?
Thank you in advance.

**Comment by lecaillon** [comment]
Thank you, your link seems not to work anymore. I used this [one](https://stackoverflow.com/questions/17070743/msbuild-inline-task-reference-is-escaping-parenthesis-sometimes) instead.
