### ISSUE TITLE
Can command line interface accept password from environment

### ISSUE THREAD

**Issue by kiranpradeep** [lecaillon/Evolve#285]
Currently when I use command line interface, the password is to be part of connection string. Is it possible to allow the password to be accepted from environment? E.g. PGPASSWORD

In devops pipelines, this lets remaining portion of connection string to be part of YML files and not necessarily be secret.

**Comment by lecaillon** [comment]
```powershell
evolve migrate postgresql -c "Server=127.0.0.1;Database=my_database;User Id=postgres;Password=$Env:PGPASSWORD"
```

This is working for me (PowerShell)
