### ISSUE TITLE
Feature request: scoping migrations

### ISSUE THREAD

**Issue by jbright** [lecaillon/Evolve#29]
Relatively common scenario is that multiple systems or services might share a primary transactional database. Multiple setup programs (or deployments) can set `MustEraseOnValidationError = false`, but you loose some functionality. 

Ideally, there'd be an optional parameter for "scope" or "namespace" so that multiple installations can use the same migrations table store for tracking, but be isolated. [Insight Database Schema does something similar](https://github.com/jonwagner/Insight.Database.Schema)

The same goal can be accomplished if I use different `MetadataTableName` but that's a little messy in the db.

**Comment by lecaillon** [comment]
Thanks for the feedback @jbright !
Actually I want to keep the whole thing dead simple, and the `MetadataTableName` parameter is exactly there for it, like you guess. I hope I don't miss your point and if I see people feel the need for such a feature I will change my mind :)
