### ISSUE TITLE
Support loading scripts from embedded resources

### ISSUE THREAD

**Issue by mhelleborg** [lecaillon/Evolve#30]
Add support for using scripts directly as embedded resources.
This simplifies some use cases and makes sure the script can be referenced the same way in all environments.

**Comment by lecaillon** [comment]
Hi, I don't have feedback where have files in a script folder is a problem either on Windows or Linux. More over hide the scripts in the assembly goes against the simplicity and the transparency goal of Evolve IMO.

**Comment by GeirGrusom** [comment]
My cases:

1. Embedded resources won't get confused by application shadowing or other such monkey business (we have an application that has made it exceptionally awkward to find file relative to the application).

2. Migrations scripts should not be altered by hand on-site, and embedded resources makes sure that doesn't happen without developer intervention.

Simply put I think it makes it easier to deploy. Also flyway supports loading migration scripts from the jar.

**Comment by ld0614** [comment]
I think this is a good option and would have avoided my issues in #76

**Comment by jouana** [comment]
Hi everyboby,

It should be cool to have this feature.

We have a WPF application with SQLite, this feature should help us for many way.

Regards.

**Comment by CaueArua** [comment]
This feature is exencial when you build an application that will run on client. If you expose the spl you have a major security breach.
Please implement this feature.

**Comment by modernist** [comment]
+1. I totally agree this is a useful feature. @lecaillon @mhelleborg if any help is needed to move this forward towards a release let me know, it's been almost a year since the PR was opened.

**Comment by lecaillon** [comment]
Let me release the Evolve 2.0 vresion. 
It's a major rework of Evolve to help simplify the overall design.
When it's finish it should let me a lot more time to add new feature like this one. Promess ;)

**Comment by lecaillon** [comment]
@GeirGrusom @ld0614 @jouana @modernist @CaueArua 

Actively working on it for the next release: Evolve 2.1.0
Thanks to @mhelleborg for its PR that helps me a lot.

I have to implement it in Evolve, but also in Evolve.MSBuild and the CLI.
Shoudn't be too long though.

### Usage

```
try
{
    var cnx = new SqliteConnection(Configuration.GetConnectionString("MyDatabase"));
    var evolve = new Evolve.Evolve(cnx, msg => _logger.LogInformation(msg))
    {
        Locations = new[] { "ConsoleApp1.db.migrations" },
        EmbeddedResourceContext = Assembly.GetExecutingAssembly()
    };

    evolve.Migrate();
}
catch (Exception ex)
{
    _logger.LogCritical("Database migration failed.", ex);
    throw;
}
```

Feel free to give me your feedback

**Comment by mhelleborg** [comment]
@lecaillon You could improve upon my original interface with a list of assembly / locations, instead of the single EmbeddedResourceContext. I think that would be better than overloading the file locations, and would support potentially loading scripts from multiple assemblies.  It also makes the interface contract less ambigous :)

**Comment by lecaillon** [comment]
@mhelleborg You think in this case something like  `ResourceFilters` is more suitable than Locations ?
So you would have 2 new properties:
- EmbeddedResourceLocations
- EmbeddedResourceFilters

**Comment by mhelleborg** [comment]
@lecaillon I was more thinking sending in a list of assemblies with a set of filters each. More or less a tuple of assembly and list of filters. 

Alternatively, just let the user provide a lambda which returns an IEnumerable of migrations. Then they can be loaded from anywhere

**Comment by lecaillon** [comment]
@mhelleborg  I need to find a structure easy to use via json or web.config/app.config files for Evolve.MSBuild or via command line options for Evolve.CLI
So 2 lists of strings separated by `;` seemed a good idea

**Comment by lecaillon** [comment]
@mhelleborg I think I will going to keep the `EmbeddedResourceContext` to avoid confusion with the  EmbeddedResource**Locations** term used by file migration scripts. So:

* Assembly[] `EmbeddedResourceContext`: one or several relative or absolute pathes to assemblies to scan
* string[] `EmbeddedResourceFilters`: zero or multiple filters to apply when searching for embedded migration scripts

In Evolve.MSBuild or Evolve.CLI those 2 properties will be a list of string where values will be separated by `;`

Everyone's ok with that ?

**Comment by mhelleborg** [comment]
@lecaillon I think I would prefer having a cleaner API, and maybe drop the functionality from the CLI. I think most of the value proposition for me is using Evolve from code, but other people might have other use cases :)

**Comment by lecaillon** [comment]
Or...

- EmbeddedResourceAssemblies
- EmbeddedResourceFilters

;)
