### ISSUE TITLE
Tool does not work the .NET 7

### ISSUE THREAD

**Issue by AndreTheHunter** [lecaillon/Evolve#302]
Please update Evolve Tool to work with .NET 7

After installing the Evolve Tool as a global tool `dotnet tool install --global Evolve.Tool` (as per https://evolve-db.netlify.app/getting-started/tool/), running it (e.g. `evolve --help`) produces the following error;

```
You must install or update .NET to run this application.

App: /Users/andre/.dotnet/tools/evolve
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (arm64)
.NET location: /Users/andre/.asdf/installs/dotnet-core/7.0.203

The following frameworks were found:
  7.0.5 at [/Users/andre/.asdf/installs/dotnet-core/7.0.203/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=arm64&rid=osx.13-arm64
```

Other global tools (like nuke), work fine.

It works fine if I switch to .NET 6 (using [asdf](https://asdf-vm.com/))

**Comment by shoaibshakeel381** [comment]
dotnet tools are always tied for runtime version, they were built for. You cannot run a tool built using .NET5 if your machine does not have .NET5 runtime installed. Seems like we just need to add .net7 in target frameworks for this to work. I could create a PR, but seems like project is pretty inactive and last commit was in Feb

**Comment by lecaillon** [comment]
Just added Evolve 3.2.0 with .NET 7 support. Enjoy
