### ISSUE TITLE
Normalize line endings when calculating checksums

### ISSUE THREAD

**Issue by mhelleborg** [lecaillon/Evolve#31]
This can be an issue when the project is being built on different systems. The same issue in flyway is detailed in [issue 253](https://github.com/flyway/flyway/issues/253)

**Comment by lecaillon** [comment]
I totally agree. Thank's again for the feedback. However I would have applied the new checksum strategy by default to all migrations, and in case of failure, calculate it the old way. This way it simplifies the code and avoid the creation of a new configuration variable like: NormalizeLineEndingsForChecksum
