### ISSUE TITLE
Version sorting

### ISSUE THREAD

**Issue by JordanMarr** [lecaillon/Evolve#313]
Should I be padding my version numbers with zeros for them to sort properly?

For example, do I need do this:
```
V1_0_0_01__CREATE_TABLE1.sql
V1_0_0_02__CREATE_TABLE2.sql
...
V1_0_0_09__CREATE_TABLE2.sql
V1_0_0_10__CREATE_TABLE2.sql
```

Or can I just do this:
```
V1_0_0_1__CREATE_TABLE1.sql
V1_0_0_2__CREATE_TABLE2.sql
...
V1_0_0_9__CREATE_TABLE2.sql
V1_0_0_10__CREATE_TABLE2.sql
```

Or, another way to ask the question: 
Does it use an alphabetical or an alphanumeric sort?

**Comment by lecaillon** [comment]
The latter
