### ISSUE TITLE
Is the timeout capped at 60 seconds somewhere?

### ISSUE THREAD

**Issue by sjd2021** [lecaillon/Evolve#314]
When running the migrations via C#, I specify the options like this:

     Evolve evolve = new Evolve(connection, (Action<string>) (msg => logger.LogInformation("Evolve log: {Message}", (object) msg)))
          {
            Locations = list,
            IsEraseDisabled = true,
            CommandTimeout = 300,
            TransactionMode = TransactionKind.CommitAll
          };

But I've noticed that the timeout seems to stop at exactly 60 seconds at which point I'll get this notification: 

> EvolveDb.EvolveSqlException: 25P02: current transaction is aborted, commands ignored until end of transaction block Sql query: SELECT pg_advisory_unlock(12345) 25P02: current transaction is aborted, commands ignored until end of transaction block\n ---> Npgsql.PostgresException (0x80004005): 25P02: current transaction is aborted, commands ignored until end of transaction block

I occasionally up the timeout for a long-running command from 30 seconds to 5 minutes, but it seems to stop at 60 seconds no matter what.

**Comment by lecaillon** [comment]
Yes sorry, not documented yet. I'll do it when I'll upgrade some part of Evolve to .NET 8

Indeed when you `TransactionMode = TransactionKind.CommitAll` Evolve will use TransactionScope and all its default settings unless you define `AmbientTransactionTimeout`

Don't hesitate to tell me if it works now with a 10 min timeout for example

Thanks

**Comment by lecaillon** [comment]
Great thanks for your feedbacks, see you :)
