### ISSUE TITLE
Support Repeatable Migrations

### ISSUE THREAD

**Issue by jcaudill** [lecaillon/Evolve#34]
Add support for repeatable migrations.  This will allow better support of databases that contain a lot of logic stored in the database.  These database objects are best supported by a state-driven engineering workflow.  For example, views, procedures, functions etc.

Having this feature will better support this workflow and greatly reduce challenges faced with wanting to use a migration-driven versioning approach.

**Comment by lecaillon** [comment]
Hi, thanks for the feedback. That's a feature I certainly want to implement soon. I'm releasing a 1.8.0 this week or so. I could think about it in the 1.9.0

**Comment by macgyver76** [comment]
Any progress on this? :)

**Comment by lecaillon** [comment]
@jcaudill @macgyver76 Can you give me more insights on how you would like this feature to be designed ? What are your use cases ?

**Comment by lecaillon** [comment]
@cfletcher How would you specifiy the order of the repeatable migrations ?

**Comment by izep** [comment]
I've done this a few times, and it's always boiled down to 'by name'. In a few cases i've had repeatable objects that rely on other repeatable objects, so I've had to name things accordingly. 

I like using this pattern for stored procs and views. I don't like having a lot of stored procs and views, but when I do, this is my preferred method. I've done it in flyway before, and their approach is reasonable.

**Comment by lecaillon** [comment]
Interresting insights @izep 
So you advise me to reproduce the flyway behavior ?

**Comment by cfletcher** [comment]
By name would be fine - that's the way roundhouse works.
I've never had more than 5/6 of these scripts and scripts haven't been order dependent. 
If any data was constrained or dependent on other data that would live within the same script.

**Comment by lecaillon** [comment]
Ok, one last question then. So repeatable scripts:
- begin with `R__` 
- are ordered by name
- are executed at the end, after all the versionned migration sctripts
- _are executed every time Evolve is run or only when their checksum changes ?_

@cfletcher @izep @jcaudill @macgyver76

**Comment by jcaudill** [comment]
that is the exactly what I’d like to see with the “Only when checksum changes” rule.

**Comment by izep** [comment]
@lecaillon Yeah, I like what you have for the first three items. For the last question:
* are executed every time Evolve is run or only when their checksum changes ?
My vote would be only when checksum changes. However, for most of my use cases, I could probably live with either. I _assume_ that only running them when their checksum changes will be faster overall.

**Comment by lecaillon** [comment]
So I would like to finish the #16 Evolve CLI before. But right after I will implement this feature as is and deployed a 1.9.0 version.

Thanks you all for the insights :)

**Comment by cfletcher** [comment]
Either would work for me, scripts are written to delete + insert or merge.
Thanks!

**Comment by macgyver76** [comment]
> Ok, one last question then. So repeatable scripts:
> 
> * begin with `R__`
> * are ordered by name
> * are executed at the end, after all the versionned migration sctripts
> * _are executed every time Evolve is run or only when their checksum changes ?_
> 
> @cfletcher @izep @jcaudill @macgyver76

@lecaillon , Shouldn't we extend this idea to run some repeatable (another set, e.g. `B_` like before) migrations **before** versioned migration scripts?

**Comment by nicumaxian** [comment]
This feature is really missing. Any progress on this?

**Comment by lecaillon** [comment]
**Question:**

In case of a modification inside a repeatable migration script, does the `Repair` command need to update its checksum accordingly, as it would have done for a standard migration ? 
My opion is no, because the goal of the repeatable migrations is to be updated to be applied another time.
What's yours?

_A little reminder: **Repair**, updates checksums of previously applied migrations with those of the currently available migration scripts._
