### ISSUE TITLE
Support to drop temporal tables in MSSQL Server

### ISSUE THREAD

**Issue by Sneezor** [lecaillon/Evolve#36]
Temporal tables follow a similar structure (period for date tange declared as row start/end), and they are not dropped automatically when performing a new migration. They return the actual error, which reads as follows: 

> Drop table operation failed on table 'myDB.mySchema.myTable' because it is not supported operation on system-versioned temporal tables.

I haven't found a way to do so manually through scripts (please let me know if I'm mistaken, I haven't found any in the docs), so it would be great if you could could perform these operations in the right order:

1. Set system versioning off: `ALTER TABLE [myTable] SET(SYSTEM_VERSIONING = OFF)`
2. Drop the period: `ALTER TABLE [myTable] DROP PERIOD FOR SYSTEM_TIME;`
3. Drop the history table. I don't know how can you do that dynamically since the name is customized, but there must be a reference somewhere.

I assume this has nothing to do with versioning, but I'm using Evolve 1.7.0 on .NET Framework 4.7 and targeting a MSSQL Server.

**Comment by lecaillon** [comment]
Hi, 
Thanks for the feedback 👍 
Evolve will support SQL Server temporal table in the next release: 1.8.0

Coming soon ;)
