### ISSUE TITLE
Evolve + Octopus

### ISSUE THREAD

**Issue by ben-foster-cko** [lecaillon/Evolve#62]
Do you have any guidance on how to integrate Evolve with Octopus. It's likely that our migrations would be run as a standalone application and since there is no command line tool (yet), I'm curious how you would recommend doing this.

Also, is it possible to disable the MS Build task?

**Comment by lecaillon** [comment]
Ok, the easy question first :) To disable the MSBuild task:
- For .NET Core projects, do not add any `evolve.json` file in your solution.
- For .NET projects, do not add any Evolve.* keys in `<appSettings>` or let the `Evolve.Command` value empty.

I dont' know Octopus. But run you migrations in a standalone application seems fair. Do not use any configuration file. Use the **in-app mode** and pass a `DbConnection` to the Evolve constructor directly.

See this [example](https://github.com/lecaillon/Evolve/blob/c4288d6385636903edc56d39e517ecc0a0d27e0e/samples/AspNetCoreSample/Startup.cs#L31) as a starting point.

Any questions :) ?

**Comment by Pvlerick** [comment]
@ben-foster-cko you can have a look at #16 and the discussion there. It is only a prototype for the moment (I lack time right now) but it is functional and I hope I'll soon be able to add the missing pieces so that we can include this is the main branch.
