### ISSUE TITLE
CREATE DATABASE in a migration

### ISSUE THREAD

**Issue by adiefrat** [lecaillon/Evolve#63]
Will appreciate the help with the next issue-
I'm working with .Net and trying to run the next migration (on MSBuild mode):
`EXEC sp_executesql N'CREATE DATABASE evolveshared'`

At the end of the build I'm getting the next error:
'EvolveException: Error executing script: V01__evolveSharedCreateDataBase.sql. CREATE DATABASE statement not allowed within multi-statement transaction. Sql query: EXEC sp_executesql N'CREATE DATABASE evolveshared' CREATE DATABASE statement not allowed within multi-statement transaction.'

When I run the same migration on SQL Management Tool (2017) it works fine and creating the asked DB.

When I'm changing the migration to the next one:
`COMMIT TRAN;
GO
EXEC sp_executesql N'CREATE DATABASE evolveshared'`
The DB is created but I'm getting a different error:
'EvolveException: Error executing script: V01__evolveSharedCreateDataBase.sql. This SqlTransaction has completed; it is no longer usable.'

**Comment by adiefrat** [comment]
Thanks for your quick response!

**Comment by lecaillon** [comment]
Ok, that's why it is not supported at all finally ^^ I remember now :) This statement dos not support transaction. And since Evolve always wraps migrations in a transaction, it fails. So while waiting for an evolution of Evolve (which could be possible when the new `SqlStatementBuilderBase` will be released by the way), use `CREATE DATABASE` in your scripts is not possible at all. Sorry

**Comment by antgel** [comment]
@lecaillon When you say "an evolution of Evolve", do you mean that this is something that will be supported at some point? If so, do you have a roadmap for this support? We might be able to support it on a professional basis.

**Comment by lecaillon** [comment]
Addressed by #150 

Evolve 2.4.0 will support SQL statements like `CREATE DATABASE` in special migrations that executes outside of a transaction. To use this feature add this comment in the first line of your migration script: `evolve-tx-off`.

```SQL
-- evolve-tx-off
create database evolveshared
```

**Comment by ahmadtaurus26** [comment]
> Addressed by #150
> 
> Evolve 2.4.0 will support SQL statements like `CREATE DATABASE` in special migrations that execute outside of a transaction. To use this feature add this comment in the first line of your migration script: `evolve-tx-off`.
> 
> ```sql
> -- evolve-tx-off
> create database evolveshared
> ```

while runnig above script getting an error that [dbname] is not exist

**Comment by RobinHiQ** [comment]
> > Addressed by #150
> > Evolve 2.4.0 will support SQL statements like `CREATE DATABASE` in special migrations that execute outside of a transaction. To use this feature add this comment in the first line of your migration script: `evolve-tx-off`.
> > ```sql
> > -- evolve-tx-off
> > create database evolveshared
> > ```
> 
> while runnig above script getting an error that [dbname] is not exist. Evolve version is 3.0.0

Did you figure this out? Getting the same issue.
