### ISSUE TITLE
Cassandra unit test projects fail with not enough replicas

### ISSUE THREAD

**Issue by lecaillon** [lecaillon/Evolve#64]
@Pvlerick 

Trying to finalize the 1.9.0 version, I came with an exception building my Cassandra test package projects, that I didn't have before. 

#### Evolve.Cassandra.AspNetCore20.Test

> EvolveSqlException: Not enough replicas available for query at consistency Serial (1 required but only 0 alive) Sql query: delete from my_keyspace.evolve_change_log where id = 0 if exists Not enough replicas available for query at consistency Serial (1 required but only 0 alive)

I think it comes from the locking strategy. All the other tests pass. I'm not too concerned about it. 
Have you got any idea ?

**Comment by Pvlerick** [comment]
Not right off the bat, but I'll take a look. What branch are you working in so I can check?

**Comment by lecaillon** [comment]
I'm back ;)
So, branch `add-command-line-interface`
Integration test: `Cli_Exe_Erase_And_Migrate_Cassandra()` for example.

Thx @Pvlerick

**Comment by gsaadeh** [comment]
@lecaillon thanks for your hard work on this tool, any ETA for 1.9? I am planning to use it along side EF core and i know you fixed some bugs related to that already. Thanks

**Comment by lecaillon** [comment]
@gsaadeh It is released by the way :)

**Comment by lecaillon** [comment]
No more issues with the Evolve 2.0.0 version
