### ISSUE TITLE
.Net Project clean error when using System.Data.SQLite to migrate

### ISSUE THREAD

**Issue by ekalaivan92** [lecaillon/Evolve#67]
## Description

On cleaning my Solution/Project getting this  Error `Unable to delete file "bin\Debug\x86\SQLite.Interop.dll". Access to the path 'xxxxx\bin\Debug\x86\SQLite.Interop.dll' is denied.`. This Error is occurred  When using `System.Data.SQLite` in our project for SQLite db support and configured `Evolve` to `Migrate` on `Build`.  

## Problem

Project Type : `Windows Service`
Frame Work : `.NET Framework, Version = v4.6.1`
Evolve: `Evolve 1.8.0.0`
Driver: `System.Data.SQLite 1.0.108.0`

In My project i have using evolve for migration and my project is pointing to SQLite db. I have using `System.Data.SQLite` Driver for db connection. I have configured the `Evolve Migration` to do migration on building the Solution/Project. Which is achieve by the `App.Config` configuration. 

App.Config looks like
```
<configuration>
     ....................
     ....................
    <appSettings>
         <add key="Evolve.ConnectionString" value="Data source = app.db" />
         <add key="Evolve.Driver" value="System.Data.SQLite" />
         <add key="Evolve.Locations" value="Migrations" />
         <add key="Evolve.Command" value="migrate" />
     </appSettings>
     ....................
     ....................  
```

When i build the Solution/Project it's working fine. At the same time if i clean the Solution/Project after the building completed. It shows an error `Unable to delete file "bin\Debug\x86\SQLite.Interop.dll". Access to the path 'xxxxx\bin\Debug\x86\SQLite.Interop.dll' is denied.`.

This `bin\Debug\x86\SQLite.Interop.dll` is used by the MSBuilder Only which is Tracked by the [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer). Ending the process of `MSBuilder` from `Task Manager` Then allows me to clean the Solution/Project.

## Steps To Produce The Error

1. Create a .Net Windows Service Project with .Net Frame Work 4.6.1
2. Add `Evolve 1.8.0.0` package from Nuget
3. Add `System.Data.SQLite 1.0.108.0` from Nuget
4. Create `Migrations` Folder in root
5. Add `Sql`(Name: `V0_0_1__initial_migration.sql`) File for initial migration. In my case i have three create table statements.
6. Add Above `<appSettings>.....</appSettings>`  configuration in the App.config file.
7. Build the Solution/Project.
8. Clean the Solution/Project. This step will gives an error.

## Additional Information:

This Issue is only causing when i am using the `System.Data.SQLite`. The package `Microsoft.Data.SQLite` doen't give this error. 

Sample Project Available @ https://github.com/ekalaivan92/EvolveTestClean

**Comment by lecaillon** [comment]
Hi @ekalaivan92 
Thanks to have taken the time to write such a clear issue. It does not appen all the times believe me :)

By the way, I already noted this issue with that driver. It seems to be link to the **.targets** file they use at build time. Look at the end of your csproj file: 
```xml
<Import Project="..\..\packages\System.Data.SQLite.Core.1.0.107.0\build\net46\System.Data.SQLite.Core.targets" Condition="Exists('..\..\packages\System.Data.SQLite.Core.1.0.107.0\build\net46\System.Data.SQLite.Core.targets')" />
```

There is a part where they copy the interop files at build time that cause the lock:
```xml
  <Target Name="CopySQLiteInteropFiles"
          Condition="'$(CopySQLiteInteropFiles)' != 'false' And
                     '$(OutDir)' != '' And
                     HasTrailingSlash('$(OutDir)') And
                     Exists('$(OutDir)')"
          Inputs="@(SQLiteInteropFiles)"
          Outputs="@(SQLiteInteropFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')">
    <!--
        NOTE: Copy "SQLite.Interop.dll" and all related files, for every
              architecture that we support, to the build output directory.
    -->
    <Copy SourceFiles="@(SQLiteInteropFiles)"
          DestinationFiles="@(SQLiteInteropFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```

I  guess if you can avoid this part and get the file by embeding it (or by any another way) it should fix your issue.

Keep me in touch

**Comment by ekalaivan92** [comment]
hi @lecaillon 
Thank you for the response. 

Your suggestion works fine. Removing that last line resolves the issue.
