### ISSUE TITLE
Unable to cast object of type 'System.SByte' to type 'System.Byte' on MySQL 

### ISSUE THREAD

**Issue by mcraa** [lecaillon/Evolve#68]
**Problem**
When i first run evolve.Migrate it fails after it creates the changelog table, then tries to
`Select id, type ... from changelog`
with the exception `Unable to cast object of type 'System.SByte' to type 'System.Byte'`

**Solution**
After i changed manually the type of the column `changelog.type` from `tinyint(4)` to `tinyint(4) unsigned` it works.

**Details**
using:
 - mysql 5.6.35
 - dotnet --version 2.1.201
 - Evolve 1.8.0
 - Pomelo.EntityFrameworkCore.MySql 2.1.1
 -- inside pomelo MySqlConnector 0.42.1

**Comment by frcandia** [comment]
Same error here.

**Comment by lecaillon** [comment]
Ok thx for the feedback. I will release a fix as soon as possible.

**Comment by ExtPro** [comment]
We got the same error. 
When is the release of version 1.9.0 planned?

**Comment by lecaillon** [comment]
Next week :)

**Comment by gsaadeh** [comment]
@lecaillon I appreciate your work on this awesome tool! Do you have any ETA for 1.9 release? I am running into this issue and cannot proceed any further. Thanks!
