### ISSUE TITLE
Optionally not run migrations on build

### ISSUE THREAD

**Issue by Sacrelicious** [lecaillon/Evolve#7]
I would like to use Evolve in our project, but we would like to run it on a build server, which does not have access to the database, so we would like to have the option to not try to run migrations on build. I'd suggest either adding a new Command that's "Ignore" (or something), or have it default to not doing anything if the Command option isn't set.

**Comment by lecaillon** [comment]
Hi @Sacrelicious 

Do nothing by default when the `Evolve.Command` is empty is a good idea.
I certainly should have done this at first, but at the time I wanted the user to set a minimum number of parameter to use Evolve.
The problem with this change is for people who use Evolve without setting this parameter.
For them it's a breaking change (a tiny one for a few of them I admit)

The less bad solution is for me to add a message in the output window when Evolve is started with `Evolve.Command` parameter empty. Like a warning: _Evolve.Command parameter is not set. None migration applied. See: https://github.com/lecaillon/Evolve/wiki/Configuration for more information._ 

Your PR #8 is just fine. 

Thanks a lot for your contribution !
