### ISSUE TITLE
Compile time error when database is missing

### ISSUE THREAD

**Issue by amiralgazi** [lecaillon/Evolve#71]
Hi

I am using the Evolve library through 'In-App' mode with .Net Core .
I came across an issue in which there is a compile time error, when the database that was written in the connection string (within config json file) is missing.

Any idea why it happens?  

Thanks in advance!

**Comment by lecaillon** [comment]
Hi,

Try to remove the `evolve.json` file. You don't need it since you use the 'In-App' mode.
If you want to keep it, the `Evolve.Command` parameter must be empty.

Keep me informed

**Comment by antgel** [comment]
@amiralgazi 's colleague here, we removed it and it worked as you suggested. Thanks @lecaillon, feel free to close. :)
