### ISSUE TITLE
Best practice for using 'Evolve' among multiple developers

### ISSUE THREAD

**Issue by amiralgazi** [lecaillon/Evolve#72]
Hi

I would like to ask a suggestion of best practice for using 'Evolve' among multiple developers with version control. i.e at the time several developers add SQL script file with the same name.
How should I deal with those occasions?

Thanks,

Amir

**Comment by lecaillon** [comment]
Hi, 

There is no silver bullet. 
First you have to decide what is the Evolve version format the team will use accross your project.
I like to take the **[app version + a counter]**. If i'm working on version **2.1.0** of my app, my first migration script will be **V2_1_0_1__create_table_article.sql**
Then  everybody increment that number and if there is a conflict,  at least you will detect it early in the process...
I imagine you can attribute a range of number in your team. One person can take number from 1 to 10, the other 11 to 20 ...
If you have a others ideas feel free to share :)
