### ISSUE TITLE
Possibility to execute migration outside of transaction

### ISSUE THREAD

**Issue by kruglik-alexey** [lecaillon/Evolve#81]
Some SQL commands can't be executed in the scope of transaction. E.g. psql `ALTER TYPE ...`. I suggest to add possibility to disable wrapping particular migration in the transaction. It can be configured via some flag in the migration file name, or via special comment inside the migration, e.g. `-- tx off`.

I'm ready to submit PR in case this changes are welcome and we agree on configuration option.

**Comment by megafinz** [comment]
@lecaillon any feedback on that?

**Comment by chrisandchris** [comment]
+1

We would also like to have that. Having issues with `CREATE EVENT SESSION` statements that can not run inside transactions. Also open to submit a pull-request.

**Comment by lecaillon** [comment]
I like the idea of a SQL comment at the very first line of a migration script. Something like:
```SQL
-- evolve-tx-off
```

What do you think ?

**Comment by chrisandchris** [comment]
I think putting that option into the script is the wrong way. Because as of now, Evolve puts _all_ scripts into a single transaction and it's either _everything_ or _nothing_ succeeds. Having an option to disable transactions would mean that a set of scripts could succeed while some others may fail.

I think this should be a global option where it's either _all_ or _none_.

**Comment by lecaillon** [comment]
@chrisandchris Evolve uses one transaction per migration script. Each time a script succeeds it is commited. So having the possiblity to disable transaction at script level allow the user to exclude from the transaction only the very few statements that do not support it.
Cf: https://github.com/lecaillon/Evolve/blob/7c1677c4b866d367b1a80e986420c27a81726ba1/src/Evolve/Evolve.cs#L374

**Comment by Zelion** [comment]
> 
> 
> Evolve uses one transaction per migration script. Every time a script succeeds it is commited. If one fails, it is rolled back and Evolve stops without executing the following scripts. See the [documentation](https://evolve-db.netlify.com/concepts/#transactions).
> 
> So having the possiblity to disable transaction at script level allow the user to exclude from the transaction only the very few statements that do not support it, by grouping them in a dedicated migration.
> 
> Thanks @chrisandchris for your feedback. I haven't been very reactive about that issue I guess :)

Hi,

I'm trying to execute 2 ALTER DATABASE in separates scripts. This will always throw a "ALTER DATABASE statement not allowed within multi-statement transaction" and the following scripts will not be executed. We tried with the `-- evolve-tx-off` comment, but no luck. Would you know what we could do to fix this issue?

The point of the ALTER DATABASE is to create a FILEGROUP and then ADD FILE to that FILEGROUP.

Thanks.

**Comment by lecaillon** [comment]
Hi,
Some ideas :
- what version of Evolve do you use ?
- do not use explicit `BEGIN TRANSACTION` in your script

**Comment by Zelion** [comment]
> 
> 
> Hi, some ideas :
> 
>     * what version of Evolve do you use ?
Evolve 2.4.0
> 
>     * do not use explicit `BEGIN TRANSACTION` in your script
I'm not

**Comment by Zelion** [comment]
Also just tried to move the logic to a STORE PROCEDURE and do an EXEC from the migration script.
The STORE PROCEDURE does work, when trying from Evolve, does not.
Also added in the SP:
`SET IMPLICIT_TRANSACTIONS OFF
SET @SQLString = 'ALTER DATABASE [' + @dbName + '] SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE;'`
and no luck

**Comment by lecaillon** [comment]
Can  you include your script if there is no private data inside ? It will help me understand the issue

**Comment by Zelion** [comment]
`DECLARE @dbName VARCHAR(15);
	DECLARE @SQLString NVARCHAR(500);
	DECLARE @physicalName VARCHAR(500);
	DECLARE @path VARCHAR(500);

	SET @dbName = DB_NAME()
	SET @physicalName = (SELECT TOP(1) physical_name FROM sys.database_files)
	SET @path = LEFT(@physicalName, CHARINDEX('\FST', @physicalName))

	SET IMPLICIT_TRANSACTIONS OFF
	SET @SQLString = 'ALTER DATABASE [' + @dbName + '] SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE;'
	EXECUTE( @SQLString )

	IF NOT EXISTS (SELECT * FROM sys.filegroups WHERE [name]='AnalysisData')
	BEGIN
		SET @SQLString =
		'ALTER DATABASE [' + @dbName + '] ' +
			'ADD FILEGROUP AnalysisData '

		EXECUTE( @SQLString )
	END

	IF NOT EXISTS (SELECT * FROM sys.database_files WHERE [name]='' + @dbName + '-AnalysisData')
	BEGIN
		SET @SQLString = 
		'ALTER DATABASE [' + @dbName + '] ' +
		'ADD FILE' +
		'(' +
			'NAME = ''' + @dbName + '-AnalysisData''' + ', ' +
			'FILENAME = ' + quotename(@path + @dbName + '-AnalysisData.ndf','''') + ',' +
			'SIZE = 5MB, ' +
			'MAXSIZE = 1000MB, ' +
			'FILEGROWTH = 5MB' +
		') ' +
		'TO FILEGROUP AnalysisData; '

		EXECUTE( @SQLString )
	END

	SET @SQLString = 'ALTER DATABASE [' + @dbName + '] SET MULTI_USER WITH ROLLBACK IMMEDIATE;'
	EXECUTE( @SQLString )
	SET IMPLICIT_TRANSACTIONS ON`

This is currently the SP we are excecuting. Worth noting we tried to separate the logic in two migration scripts before trying this.

**Comment by lecaillon** [comment]
Where is the `-- evolve-tx-off` ?

**Comment by Zelion** [comment]
This is the migration script:
`-- evolve-tx-off
EXEC StoreFileGroupTest;`

**Comment by lecaillon** [comment]
You EXEC in the comment ?

**Comment by Zelion** [comment]
No, I'm new to the Insert Code in GitHub, for some reason it's not recognizing the line breaks

`-- evolve-tx-off 
EXEC StoreFileGroupTest;`

**Comment by lecaillon** [comment]
You can **preview** before posting a comment by the way.

Is the `EXEC StoreFileGroupTest;` in the separate migration script ? After the migration script that create the stored procedure ?

**Comment by Zelion** [comment]
I created the SP manually in the DB to test this, and yes, the EXEC line is in the migration script.

**Comment by lecaillon** [comment]
Evolve search for -- evolve-tx-off in the first line of the script. Is this the case ?

**Comment by Zelion** [comment]
Yes, I have only this 2 lines in the script:
`-- evolve-tx-off`
`EXEC StoreFileGroupTest;`

**Comment by lecaillon** [comment]
You could try to mimic what Evolve does in a ConsoleApp and tell me if it works :

```
[...]
cmd.CommandText = "EXEC StoreFileGroupTest;";
cmd.ExecuteNonQuery();
```

**Comment by Zelion** [comment]
It works

**Comment by lecaillon** [comment]
Well, I don't have any idea. Maybe simplify the SP until it passes to isolate the issue.
And if you run Evolve from your app, post the code you use to run Evolve
