### ISSUE TITLE
EvolveConfigurationException: Prefix V not found in sql

### ISSUE THREAD

**Issue by kadamnitin** [lecaillon/Evolve#9]
my sql script file name is V1_0_0__build_1_0_0_7.sql

following  error occured while migrating
Evolve : error : EvolveConfigurationException: Prefix V not found in sql file

**Comment by lecaillon** [comment]
Hi, 

I cannot reproduce your error.
I've just tested a migration with the filename you talk about and it succeeded. Here is the result I have:
_Successfully applied migration V1_0_0__build_1_0_0_7.sql._

Could you please verify the name of your file ?
If the problem still occured, paste me a copy of the output window you have.
And give me some infos like the version of Evolve, the version of the .NET framework you use...

**Comment by kadamnitin** [comment]
Evolve version 1.3.1
Dot Net Framework 4.0

config :

<add key="Evolve.ConnectionString" value="Connection.PPE"/>
		<add key="Evolve.Driver" value="sqlserver" />
	
		<add key="Evolve.Locations" value="Sql_Scripts" />
		<add key="Evolve.Command" value="migrate" />

Error :


 Migration folder Sql_Scripts copied to c:\jenkins\Web\obj\TEST\Sql_Scripts.
  Executing Migrate...
  Evolve initialized.
  No metadata found.
Evolve : error : EvolveConfigurationException: Prefix V not found in sql file name: c:\jenkins\Web\obj\TEST\Sql_Scripts\V1_0_0__build_1_0_0_7.sql. 
Evolve : error :    at Evolve.Utilities.MigrationUtil.ExtractVersionAndDescription(String script, String prefix, String separator, String& version, String& description) 
Evolve : error :    at Evolve.Migration.FileMigrationLoader.LoadMigrationFromFile(String script, String prefix, String separator) 
Evolve : error :    at Evolve.Migration.FileMigrationLoader.<>c__DisplayClass2_0.<GetMigrations>b__2(FileInfo f) 
Evolve : error :    at System.Collections.Generic.List`1.ForEach(Action`1 action) [c:\jenkins\workspace\PersonalPropertyExpress\DotNetPersonalPropertyExpress\Cogitate.PPE.Web\Cogitate.PPE.Web\Cogitate.PPE.Web.csproj]
Evolve : error :    at Evolve.Migration.FileMigrationLoader.GetMigrations(IEnumerable`1 locations, String prefix, String separator, String suffix)
Evolve : error :    at Evolve.Evolve.Migrate() 
Evolve : error :    at Evolve.Evolve.ExecuteCommand() 
Evolve : error :    at Evolve.MsBuild.EvolveBoot.Execute() 
Evolve : error :  


thanks in avance;

**Comment by lecaillon** [comment]
I reproduced the error. It is due to the .NET framework version you use. As specified in the wiki the min verison supported is .NET 4.5.1+
I don't know why Nuget let you download the package without a warning ? 
By the way, .NET 4.0 is not supported by Microsoft anymore. Me neither.

So if you want to use Evolve, update your .NET framework.
