### ISSUE TITLE
Add a standalone Evolve CLI for win-64 and linux-64

### ISSUE THREAD

**Issue by lecaillon** [lecaillon/Evolve#90]

**Comment by iainnicol** [comment]
I think it would be really convenient to package the new Evolve CLI as a .NET Core Global Tool. It would let us install with ``dotnet tool install -g Evolve.Cli``, and run with a simple ``evolve``.  This should work on Windows, Linux, and MacOS.

We could then add Evolve to the list at https://github.com/natemcmaster/dotnet-tools.

I'm about to open a pull request.  But unfortunately I just realised it breaks the integration tests. So it is not ready to merge.

**Comment by lecaillon** [comment]
It could be a good idea indeed. 
By the way I'm working on a big refactoring of Evolve. You can begin to see the code in the branch `evolve-2.0.0`
So do not lost your time with previsous unit tests. ;) This new version of Evolve changes a lot of things about it.

**Comment by lecaillon** [comment]
Addressed in #99
