### ISSUE TITLE
Move CI from Travis CI to Azure DevOps

### ISSUE THREAD

**Issue by lecaillon** [lecaillon/Evolve#91]
Before logging a new issue, please have a quick read through the [contribution guidlines](https://github.com/lecaillon/Evolve/blob/master/CONTRIBUTING.md).

**Comment by lecaillon** [comment]
Addressed in #99

**Comment by oooolivierrrr** [comment]
Just wondering, I've cloned the project on my azure devops repo and used the corresponding yaml for devops but i get a weird error :
/azure-pipelines.yml (Line: 2, Col: 12): Unexpected vmImage 'Hosted Ubuntu 1604'

I checked twice when creating the CI pipeline to use the 'Hosted Ubuntu 1604' as a build agent.

Any clue ?
