### ISSUE TITLE
Set schema to searchPath for PostgresSQL

### ISSUE THREAD

**Issue by MikhailBondarchuk** [lecaillon/Evolve#95]
_Postgres 10.5
.netcore 2.1
evolve 1.9_

**Steps to reproduce:**
1) use in-app mode
2) set schema 'test' to Evolve.Schemas
3) set schema 'test' to Evolve.MetadataTableSchema
4) set Evolve.Location and add scripts which create tables
5) run migration on empty database
6) tables created in public schema, but I expected they created in schema 'test'

**Comment by lecaillon** [comment]
Evolve will not inferred in the execution of your queries. So it is your responsibility to use the schema you want.
When you define `Evolve.Schemas`, you tell Evolve to create the schemas if they do not already exist. For eventually be able to erase them later with the **Erase** `Evolve.Command`. Evolve is _in charge_ of the schemas you listed. It is an optional paramter.
When you define `Evolve.MetadataTableSchema` you tell Evolve to create its _history_ table called **changelog** in this specific schema.

**Comment by MikhailBondarchuk** [comment]
This issue force me to add schema to search path in the connection string.
But I expect to use first schema from Schemas as default instead of 'public' same as MetadataTableSchema uses first schema as default.
This case will be very common.
You can add this logic with special config parameter, just for usability.

**Comment by lecaillon** [comment]
It is not an issue. Evolve runs the scripts it finds in the locations with the connection you provide without change anything that does not concern it.
You must provide scripts which would have worked outside the Evolve context. 
For example, if you only use Evolve in dev, because your DBA wants to execute them himself in prod, it must work in the same way.

**Comment by MikhailBondarchuk** [comment]
My case another, I get schema name from config and I don't want use templates because DBA runs that scripts from console in some cases. He changes search path and uses tables without schema name. Anyway, thanks for reply.

**Comment by lecaillon** [comment]
Ok, thx for your feedback
