### ISSUE TITLE
How to force old version sql script to run

### ISSUE THREAD

**Issue by amiralgazi** [lecaillon/Evolve#96]
I've recently created a .Net Core project using Evolve In-App mode.
At the company I work for, we came across an issue in which several developers try to add their own script, but sometimes some scripts don't run, because of different upload times to git (when each developer finish to develop different feature).

Our scripts' name convention is: 
    VSERIAL_ISODATE_TIME__SOME_USEFUL_NAME
For example:
    V0001_20190117_1658__add_column_x

The issue:
Suppose we have 3 developers who want to upload their own script version.
Developer one - script V0001_20190117_1658__add_column_x
Developer two - script V0002_20190117_1658__add_column_y
Developer three - script V0003_20190117_1658__add_column_z

Those scripts will be migrated into database only if they exist in visual studio ordered by their number.
However, if script V0001 and script V0003 have already run, then script V0002 will not run.

I would like to ask if there is a way to force script V0002 to run after V0003 has already run?

**Comment by lecaillon** [comment]
Yes by setting `OutOfOrder` to `true`
https://evolve-db.netlify.com/configuration/#options

**Comment by amiralgazi** [comment]
@lecaillon Thanks for your help! this really helps
